- Example/Split/GetTreatmentViewController.swift
- Example/Split/TrackViewController.swift
- Split.xcodeproj/project.pbxproj
- Split/Events/SplitEventActionTask.swift
- Split/SplitClient.swift
- Split/SplitClientProtocol.swift
- Split/Version.swift
New added method receives a closure instead of SplitTaskEvent object.
> Added new method to register handler for SDK events

- CHANGES.txt
- Example/Split.xcodeproj/project.pbxproj
- Example/Split.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Example/Split/Info.plist
- Split.podspec
- Split/Info.plist
- Version files updated to version 1.20
- xcode 9.4 migration
> Version 1.2.0 setup

- Split.podspec
- Split/Fetcher Engine/Refresh/RefreshableMySegmentsFetcher.swift
- Split/Fetcher Engine/Refresh/RefreshableSplitFetcher.swift
- Split/Storage/FileStorage.swift
- Split/Track/FileStorageManager.swift
- Split/Version.swift
Changed cache directory on device
> Changed cache directory

- Split.podspec
- Split/Api/SplitClient.swift
- Split/Api/SplitFactory.swift
- Split/Common/Utils/Version.swift
- Split/Events/SplitEventsManager.swift
- Split/FetcherEngine/HttpMySegmentsFetcher.swift
- Split/FetcherEngine/HttpSplitChangeFetcher.swift
- Split/FetcherEngine/Refresh/RefreshableMySegmentsFetcher.swift
- Split/FetcherEngine/Refresh/RefreshableSplitFetcher.swift
- Split/PostTasks/Common/PeriodicDataTask.swift
- Split/PostTasks/Metrics/MetricsManager.swift
- Split/Secure/SecureDataStore.swift
- Metrics manager implementation
- Metrics added to Split changes fetcher, segments fetcher, get treatment and secure storage
- Refactored project tree
- Fixed some classes and functions scope
- Small code refactor in some classes
> SDKS-193: Internal metrics implementation

- CHANGES.txt
- Split.podspec
- Split.xcodeproj/project.pbxproj
- Split/Common/Utils/CastUtils.swift
- Split/Common/Utils/Version.swift
- Split/Matchers/BetweenMatcher.swift
- Split/Matchers/EqualToMatcher.swift
- Split/Matchers/GreaterThanOrEqualToMatcher.swift
- Split/Matchers/LessThanOrEqualToMatcher.swift
- SplitTests/Helpers/CsvHelper.swift
- SplitTests/Helpers/FileHelper.swift
- SplitTests/MatcherEvalTests.swift
- SplitTests/Resources/matchers.json
Workaround applied to fix a cast from Any to Int64 that was causing an incorrect evaluation.
> SDKS-300: Incorrect treatment result

- CHANGES.txt
- Split.podspec
- Split.xcodeproj/project.pbxproj
- Split/Common/Utils/Version.swift
- Split/Engine/Engine.swift
- SplitTests/EngineTests.swift
- SplitTests/Helpers/CsvHelper.swift
- SplitTests/Helpers/FileHelper.swift
Simple fix for issue when retrieved algorithm from server is null
> SDKS-354: Fixed issue when algo nil from server

- Split.xcodeproj/project.pbxproj
- Split/Common/Utils/Version.swift
- Split/Engine/Engine.swift
- SplitTests/Fake/SplitterAllocationFake.swift
- SplitTests/Helpers/SplitHelper.swift
- SplitTests/Resources/split_traffic_allocation_1.json
- SplitTests/TrafficAllocationTest.swift
- Fixed issue as specified in [document](https://splitio.atlassian.net/wiki/spaces/EN/pages/236912690/Traffic+Allocation+issue+on+1).
- Added test case for the issue.
> SDKS-346: Fixed traffic allocation equal to 1 issue

- Split/Api/SplitClient.swift
- Split/Engine/Engine.swift
Fix intended to remove a non easy to reproduce issue when using bucketing key
> SDKS-419: Splitter crash when get treatment call

- Split.podspec
- Split/Api/DefaultSplitClient.swift
- Split/Api/DefaultSplitFactoryBuilder.swift
- Split/Api/DefaultSplitManager.swift
- Split/Common/Utils/Version.swift
- SplitTests/SplitFactoryBuilderTests.swift
- SplitTests/SplitManagerTest.swift
> SDKS-32: Input validation

- Split.xcodeproj/project.pbxproj
- Split/Api/DefaultSplitClient.swift
- Split/Api/LocalhostSplitClient.swift
- Split/Api/SplitClient.swift
- Split/Api/SplitResult.swift
- Split/Common/Validators/ValidatorMessageLogger.swift
- Split/PostTasks/Metrics/MetricsManager.swift
- SplitIntegrationTests/Info.plist
- SplitIntegrationTests/SplitIntegrationTests.swift
- SplitTests/Fake/InternalSplitClientStub.swift
- Added treatment with config methods
> SDKS-582: Treatment with config methods

- CHANGES.txt
- Split.podspec
- Split.xcodeproj/project.pbxproj
- Split/Common/Utils/Version.swift
- Split/Engine/Engine.swift
- SplitTests/EngineTests.swift
- SplitTests/Resources/split_traffic_alloc_50_default_rule_50.json
- Fixing traffic allocation issue on certain scenarios
> Release 2.0.3

- CHANGES.txt
- Split.podspec
- Split.xcodeproj/project.pbxproj
- Split/Api/DefaultSplitClient.swift
- Split/Api/LocalhostSplitClient.swift
- Split/Api/SplitClient.swift
- Split/Api/SplitClientConfig.swift
- Split/Common/Extensions/Array+DynamicCodable.swift
- Split/Common/Extensions/Dictionary+DynamicCodable.swift
- Split/Common/Utils/Version.swift
- Split/Common/Validators/EventValidator.swift
- Split/Common/Validators/ValidationConfig.swift
- Split/Common/Validators/ValidationErrorInfo.swift
- Split/Network/DataParsing/Json.swift
- Split/Network/Endpoints/RestClient+TrackEvents.swift
- Split/Network/Targets/EnvironmentTargetManager.swift
- Split/PostTasks/Track/Models/EventDTO.swift
- Split/PostTasks/Track/Models/EventsFile.swift
- Split/PostTasks/Track/Models/EventsHit.swift
- Split/PostTasks/Track/TrackManager.swift
- SplitTests/Fake/InternalSplitClientStub.swift
- SplitTests/Fake/Network/RestClientStub.swift
- SplitTests/TrackManagerTest.swift
- SplitTests/ValidatorsTests/EventValidatorTests.swift
> Release 2.2.0

- Split/Api/DefaultSplitClient.swift
- Split/Api/DefaultSplitManager.swift
- Split/Common/Validators/SplitValidator.swift
- Split/Common/Validators/ValidationErrorInfo.swift
- SplitTests/ValidatorsTests/SplitValidatorTests.swift
> SDKS-756 Logging warning instead of error when split not found

- Split/Common/Utils/Version.swift
- Split/Engine/DefaultTreatmentManager.swift
- Split/Engine/Evaluator.swift
- SplitTests/Integration/SplitIntegrationTest.swift
- Fixed issue in evaluator
- Added integration test
> SDSK-962: Missing change number when sending impressions to BE

- .github/pull_request_template.md
- CHANGES.txt
- CONTRIBUTORS-GUIDE.md
- Detailed-README.md
- README.md
https://splitio.atlassian.net/browse/SDKS-911
> Documentation revamp

- Split/Api/DefaultSplitClient.swift
- Split/Api/DefaultSplitFactory.swift
- Split/Events/Executors/SplitEventExecutorResources.swift
- Split/Events/Executors/SplitEventExecutorWithClient.swift
- SplitTests/Integration/SplitIntegrationTest.swift
- Refactored client and factory to initialize components in factory instead of client
- Preventing some possibe memory leak in event manager resources. 
- Improved tests
> SDKS-1077: Moving inicialization from client to factory. 

- Split.xcodeproj/project.pbxproj
- Split/Api/DefaultSplitFactory.swift
- Split/Api/LocalhostSplitFactory.swift
- Split/Api/SplitClient.swift
- Split/Api/SplitFactory.swift
- Split/Common/Utils/Version.swift
- Split/Info.plist
- Split/Network/Targets/DynamicTarget.swift
- SplitTests/VersionTest.swift
Added a static version property to SplitClient
Created a VersionTest class
> SDKS-1198:  Static sdk version prop

- .travis.yml
- Split.xcodeproj/project.pbxproj
- Split.xcodeproj/xcshareddata/xcschemes/Split.xcscheme
- SplitTests/MySegmentsFetcherTests.swift
- SplitTests/SplitChangeFetcherTests.swift
Update project to settings recommended by xcode 11.2.1 previous to merge a user PR removing some warnings.
Upgrade swift version and improved some code
Running all tests
> SDKS-1199: Update project settings

- SplitTests/FactoryMonitorTest.swift
- SplitTests/FactoryRegistryTest.swift
- SplitTests/SplitConfigurationsParsingTest.swift
- SplitTests/SplitFactoryBuilderTests.swift
Removed some warnings on tests produced when upgrading to xcode 11
Running all tests
> Fix xcode11 test warnings

- Split/Api/DefaultSplitFactory.swift
- Split/Api/LocalhostSplitFactory.swift
- Split/Api/SplitFactory.swift
- SplitTests/VersionTest.swift
Make this method available to Objective C
> SDKS-1198: Static SDK version prop

- CHANGES.txt
- Split.podspec
- Split.xcodeproj/project.pbxproj
- Split/Api/DefaultSplitClient.swift
- Split/Common/Utils/NotificationsHelper.swift
- Split/Common/Utils/Version.swift
- Split/Engine/Evaluator.swift
- Split/Events/Executors/SplitEventExecutorWithClient.swift
- Split/Impressions/DefaultImpressionsManager.swift
- Split/Models/Condition.swift
- Split/Models/Matcher.swift
- Split/Track/DefaultTrackManager.swift
- SplitTests/EvaluatorTests.swift
- SplitTests/TreatmentManagerTest.swift
Fixed some  strong reference cycles to avoid leaking memory
> SDkS-1278: Memory issue

- Split/Track/Models/EventDTO.swift
- SplitTests/EventDTOJsonTest.swift
Adding a new check for boolean and string. Also added UT
> SDKS-1579: Fixed issue with boolean in workaround

- CHANGES.txt
- Split.podspec
- Split.xcodeproj/project.pbxproj
- Split/Common/Utils/Version.swift
- Split/Impressions/DefaultImpressionsManager.swift
- SplitTests/Helpers/TestUtils.swift
- SplitTests/Integration/SplitChangesTest.swift
- SplitTests/Integration/SplitIntegrationTest.swift
Correctly remove impressions before sending to server
> Fixing duplicated impressions issue

- CHANGES.txt
- Split.podspec
- Split.xcodeproj/project.pbxproj
- Split/Api/DefaultSplitFactory.swift
- Split/Api/SplitClientConfig.swift
- Split/Common/Utils/Version.swift
- Split/FetcherEngine/Cache/InMemorySplitCache.swift
- Split/FetcherEngine/Cache/SplitCache.swift
- Split/FetcherEngine/Cache/SplitCacheProtocol.swift
- Split/FetcherEngine/Cache/SplitChangeCache.swift
- Split/FetcherEngine/Refresh/DefaultRefreshableSplitFetcher.swift
- Split/Impressions/DefaultImpressionsManager.swift
- Split/Track/Models/EventDTO.swift
- SplitTests/EventDTOJsonTest.swift
- SplitTests/Fake/SplitCacheStub.swift
- SplitTests/Fake/SplitChangeFetcherStub.swift
- SplitTests/Fake/SplitEventsManagerStub.swift
- SplitTests/Helpers/TestUtils.swift
- SplitTests/Integration/SplitChangesTest.swift
- SplitTests/Integration/SplitIntegrationTest.swift
- SplitTests/RefreshableSplitFetcherTest.swift
> Release 2.5.3

- Split.xcodeproj/project.pbxproj
- Split/Api/SplitClientConfig.swift
- Split/Api/SplitFilter.swift
- Split/Api/SyncConfig.swift
- Split/Common/Validators/SplitValidator.swift
- Split/FetcherEngine/Cache/SplitCache.swift
- SplitTests/SplitFilter/SyncConfigTest.swift
Added Split sync config
- Unit tests
> SDKS-1862: Split filter config (Fetch specific splits)

- Split.xcodeproj/project.pbxproj
- Split/Api/FilterBuilder.swift
- Split/Api/SyncConfig.swift
- SplitTests/SplitFilter/FilterBuilderTest.swift
> SDKS-1863: Filter builder (Fetch specific splits)

- CHANGES.txt
- Split.podspec
- Split/Api/SplitFilter.swift
- Split/Common/Utils/Version.swift
- Split/Network/Targets/DynamicTarget.swift
- SplitTests/EnvironmentTargetManagerTest.swift
Removing default parameters in enum
> Default params enums fix

- Split.xcodeproj/project.pbxproj
- Split/Common/Utils/Atomic.swift
- Split/Network/HttpClient/HttpDataRequest.swift
- Split/Network/HttpClient/HttpRequest.swift
- Split/Network/HttpClient/HttpStreamRequest.swift
- Split/Network/Streaming/EventStreamParser.swift
- Split/Network/Streaming/ReconnectBackoffCounter.swift
- Split/Network/Streaming/SseAuthenticator.swift
- Split/Network/Streaming/SseClient.swift
- Split/Network/Streaming/SseConnectionManager.swift
- Split/Network/Streaming/Timers.swift
- SplitTests/Fake/Network/HttpStreamRequestMock.swift
- SplitTests/Fake/ReconnectBackoffCounterStub.swift
- SplitTests/Fake/SseAuthenticationStub.swift
- SplitTests/Fake/SseClientMock.swift
- SplitTests/Fake/SseClientStub.swift
- SplitTests/Fake/TimersManagerMock.swift
- SplitTests/Streaming/EventStreamParserTest.swift
- SplitTests/Streaming/ReconnectBackoffCounterTest.swift
- SplitTests/Streaming/SseClientTest.swift
- SplitTests/Streaming/SseConnectionManagerTest.swift
- Added streaming connection manager and tests
- Added stream parsing to SSE client and updated tests
> SDKS-1886: SSE connection manager

- Split.xcodeproj/project.pbxproj
- Split/Common/Structs/SyncDictionarySingleWrapper.swift
- Split/Network/Streaming/Timers.swift
- SplitTests/Fake/TimersManagerMock.swift
- SplitTests/Streaming/TimersManagerTest.swift
- Added timers manager implementation and tests
> SDKS-1886: Timers manager

- Split.xcodeproj/project.pbxproj
- Split/FetcherEngine/Cache/InMemorySplitCache.swift
- Split/FetcherEngine/Cache/SplitCache.swift
- Split/FetcherEngine/Cache/SplitCacheProtocol.swift
- Split/Network/Errors/GenericError.swift
- Split/Network/Streaming/DefaultSseNotificationParser.swift
- Split/Network/Streaming/SseNotificationProcessor.swift
- Split/Network/Streaming/SseNotifications.swift
- Split/Network/Streaming/SyncUpdateWorker.swift
- Split/Network/Streaming/Synchronizer.swift
- SplitTests/Fake/MySegmentsCacheStub.swift
- SplitTests/Fake/SplitCacheStub.swift
- SplitTests/Fake/SseNotificationParserStub.swift
- SplitTests/Fake/SynchronizerStub.swift
- SplitTests/Fake/UpdateWorkerMock.swift
- SplitTests/Streaming/NotificationParserTest.swift
- SplitTests/Streaming/SseNotificationProcessorTest.swift
- SplitTests/Streaming/SyncUpdateWorkerTest.swift
- Added notification processor and workers
- Added unit test for new components
> SDKS-1688: Notification processor

- Split.xcodeproj/project.pbxproj
- Split/Network/Streaming/PushManagerEventBroadcaster.swift
- Split/Network/Streaming/Timers.swift
- SplitTests/Streaming/PushManagerEventBroadcasterTest.swift
- Added push notification broadcaster  channel and tests
> SDKS-1686: SSE Broadcaster channel

- Split/Api/DefaultSplitFactory.swift
- Split/Common/Utils/Atomic.swift
- Split/FetcherEngine/Cache/SplitChangeCache.swift
- Split/FetcherEngine/HttpSplitChangeFetcher.swift
- Split/FetcherEngine/Refresh/PeriodicSyncWorker.swift
- Split/Network/Streaming/BackoffCounterTimer.swift
- Split/Network/Streaming/DefaultSseNotificationParser.swift
- Split/Network/Streaming/NotificationManagerKeeper.swift
- Split/Network/Streaming/PushNotificationManager.swift
- Split/Network/Streaming/SseClient.swift
- Split/Network/Streaming/SseHandler.swift
- Split/Network/Streaming/SseNotifications.swift
- Split/Network/Streaming/SyncManager.swift
- Split/Network/Streaming/SyncManagerBuilder.swift
- Split/Network/Streaming/Synchronizer.swift
- SplitTests/Fake/Streaming/SseClientMock.swift
- SplitTests/Fake/Streaming/SseNotificationParserStub.swift
- Improvig notifications models to avoid issues with 32bit devices
- Improving bg-fg logic to handle app host bg-fg
> SDKS-1697: push notification polishing

- Split/FetcherEngine/HttpSplitChangeFetcher.swift
- Split/FetcherEngine/Refresh/RetryableSyncWorker.swift
- Added new change number check when fetching split on notification update received
> Adding check to fetch until last change is retrieved

- Split.xcodeproj/project.pbxproj
- Split/Info.plist
- Split/Storage/SplitDatabase.swift
- Split/Storage/models/EventEntity.swift
- Split/Storage/models/GeneralInfoEntity.swift
- Split/Storage/models/ImpressionEntity.swift
- Split/Storage/models/MySegmentEntity.swift
- Split/Storage/models/SplitEntity.swift
- Split/Storage/split_cache.xcdatamodeld/split_cache.xcdatamodel/contents
- Created model, database stack and entities
> SDKS-1286: Storage revamp initial setup

- .gitignore
- Cartfile.resolved
- Split.xcodeproj/project.pbxproj
- Split/Storage/CoreDataHelper.swift
- Split/Storage/Events/EventDao.swift
- Split/Storage/Events/EventEntity.swift
- Split/Storage/Events/PersistentEventsStorage.swift
- Split/Storage/SplitDatabase.swift
- Split/Storage/split_cache.xcdatamodeld/split_cache.xcdatamodel/contents
- Split/Track/Models/EventDTO.swift
- SplitTests/Fake/Storage/EventDaoStub.swift
- SplitTests/Fake/Storage/IntegrationCoreDataHelper.swift
- SplitTests/Fake/Storage/SplitDatabaseStub.swift
- SplitTests/Integration/DestroyTest.swift
- SplitTests/Integration/FetchSpecificSplitsTest.swift
- SplitTests/Integration/FlushTest.swift
- SplitTests/Integration/MySegmentServerErrorTest.swift
- SplitTests/Integration/MySegmentUpadatedTest.swift
- SplitTests/Integration/SplitChangesServerErrorTest.swift
- SplitTests/Integration/SplitChangesTest.swift
- SplitTests/Integration/SplitIntegrationTest.swift
- SplitTests/Integration/Storage/EventDaoTests.swift
- SplitTests/SplitChangeFetcherTests.swift
- SplitTests/Storage/EventDaoTests.swift
- SplitTests/Storage/PersistentEventsStorageTest.swift
- SplitTests/Streaming/PushNotificationManagerTest.swift
- Added Common core data logic
- Added EventDao component
- Added PersistentEventsStorage
- Tests for new components
> SDK-S1292: Events storage components

- Split.xcodeproj/project.pbxproj
- Split/FetcherEngine/HttpSplitFetcher.swift
- Split/FetcherEngine/Refresh/PeriodicSyncWorker.swift
- Split/FetcherEngine/Refresh/RetryableSyncWorker.swift
- Split/Network/HttpClient/HttpError.swift
- Split/Storage/Splits/PersistentSplitsStorage.swift
- Split/Storage/Splits/ProcessedSplitChange.swift
- Split/Storage/Splits/SplitsStorage.swift
- SplitTests/Fake/MetricsManagerStub.swift
- SplitTests/Fake/Network/RestClientStub.swift
- SplitTests/Fake/Service/HttpSplitFetcherStub.swift
- SplitTests/Fake/Service/SplitChangeProcessorStub.swift
- SplitTests/Fake/Storage/PersistentSplitsStorageStub.swift
- SplitTests/Fake/Storage/SplitsStorageStub.swift
- SplitTests/PeriodicSplitsSyncWorkerTest.swift
- SplitTests/Service/HttpSplitFetcherTests.swift
- SplitTests/SplitsSyncWorkerTest.swift
- Simplified split fetcher
- Tests
> SDKS-1290:  Split fetcher (Storage revamp)

- Split.xcodeproj/project.pbxproj
- Split/Api/SplitApiFacade.swift
- Split/FetcherEngine/NewHttpMySegmentsFetcher.swift
- Split/FetcherEngine/OldHttpMySegmentsFetcher.swift
- SplitTests/Fake/MetricsManagerStub.swift
- SplitTests/MySegmentsFetcherTests.swift
- SplitTests/Service/HttpMySegmentsFetcherTests.swift
> SDKS-1298: Mysegments fetcher (revamp)

- Split.xcodeproj/project.pbxproj
- Split/FetcherEngine/Recorder/ImpressionsRecorder.swift
- Split/FetcherEngine/Recorder/ImpressionsRecorderWorker.swift
- Split/FetcherEngine/Recorder/RecorderWorker.swift
- SplitTests/Fake/Service/HttpImpressionsRecorderStub.swift
- SplitTests/Fake/Storage/PersistentImpressionsStorageStub.swift
- SplitTests/Helpers/TestingHelper.swift
- SplitTests/Service/HttpImpressionsRecorderTests.swift
- SplitTests/Service/ImpressionsRecorderWorkerTests.swift
- Added impressions recorder components and tests
> SDKS-1300: Impressions recorder (Impressions revamp)

- Split.xcodeproj/project.pbxproj
- Split/FetcherEngine/HttpMySegmentsFetcher.swift
- Split/FetcherEngine/HttpSplitFetcher.swift
- Split/FetcherEngine/Refresh/PeriodicSyncWorker.swift
- Split/FetcherEngine/Refresh/RetryableSyncWorker.swift
- Split/Storage/CoreDataHelper.swift
- Split/Storage/Events/EventDao.swift
- Split/Storage/GeneralInfo/GeneralInfoDao.swift
- Split/Storage/Impressions/ImpressionDao.swift
- Split/Storage/MySegments/MySegmentsDao.swift
- Split/Storage/MySegments/PersistentMySegmentsStorage.swift
- Split/Storage/SplitDatabase.swift
- Split/Storage/Splits/PersistentSplitsStorage.swift
- Split/Storage/Splits/SplitDao.swift
- Split/Storage/Splits/SplitsStorage.swift
- SplitTests/Service/HttpMySegmentsFetcherTests.swift
> Applied some linter fixes

- Split/Api/DefaultSplitFactory.swift
- Split/Api/LocalhostSplitClient.swift
- Split/Api/SplitApiFacade.swift
- Split/FetcherEngine/Recorder/RecorderWorker.swift
- Split/FetcherEngine/Refresh/PeriodicSyncWorker.swift
- Split/FetcherEngine/Refresh/RetryableSyncWorker.swift
- Split/FetcherEngine/Refresh/YamlSplitsStorage.swift
- Split/Network/Streaming/RetryableSplitsUpdateWorkerFactory.swift
- Split/Network/Streaming/Synchronizer.swift
- Split/Storage/Impressions/ImpressionDao.swift
- SplitTests/SplitsSyncWorkerTest.swift
- SplitTests/SplitsUpdateWorkerTest.swift
- Linter issues and some component renaming
> SDKS-2365 cache revamp polishing

- CHANGES.txt
- Split.podspec
- Split/Api/DefaultSplitFactory.swift
- Split/Common/Utils/Version.swift
- Split/FetcherEngine/Refresh/RetryableSyncWorker.swift
- Split/Network/Streaming/SyncManager.swift
- Split/Network/Streaming/Synchronizer.swift
- Split/Storage/FileStorage.swift
- Split/Storage/Splits/SplitsStorage.swift
- SplitTests/Fake/Storage/PersistentSplitsStorageStub.swift
- SplitTests/Fake/Storage/SplitsStorageStub.swift
- SplitTests/Fake/Streaming/SynchronizerStub.swift
- SplitTests/Integration/SplitIntegrationTest.swift
- SplitTests/Streaming/SyncManagerTest.swift
- SplitTests/Streaming/SynchronizerTest.swift
- SplitTests/TreatmentManagerTest.swift
- Loading cache data on init
- Updated UT and Integration
> SDKS-2381: Initial cache loading

- Split.podspec
- Split.xcodeproj/xcshareddata/xcschemes/Split.xcscheme
- Split/Common/ServiceConstants.swift
- Split/Common/Utils/Atomic.swift
- Split/Common/Utils/Version.swift
- Split/FetcherEngine/HttpSplitFetcher.swift
- Split/FetcherEngine/Refresh/PeriodicSyncWorker.swift
- Split/FetcherEngine/Refresh/RetryableSyncWorker.swift
- Split/Models/Condition.swift
- Split/Models/Matcher.swift
- Split/Network/HttpClient/HttpClient.swift
- Split/Network/HttpClient/HttpDataRequest.swift
- Split/Network/HttpClient/HttpRequest.swift
- Split/Network/RestClient/RestClient+SplitChanges.swift
- Split/Network/RestClient/RestClient.swift
- Split/Network/Streaming/RetryableSplitsUpdateWorkerFactory.swift
- Split/Storage/CoreDataHelper.swift
- SplitTests/Fake/Network/RestClientStub.swift
- SplitTests/Fake/Service/HttpSplitFetcherStub.swift
- SplitTests/PeriodicSplitsSyncWorkerTest.swift
- SplitTests/Service/HttpSplitFetcherTests.swift
- Avoiding cache when updating splits after push received
- Adding logic to handle some possible thread race conditions
> SDKS-2382: Thread, cache and memory improvements. 

- Split.xcodeproj/project.pbxproj
- Split/Common/Extensions/Bundle+Finder.swift
- Split/Storage/CoreDataContextBuilder.swift
- Fix for data model bundle when using SPM
> Fix to find the data model when using spm

- Split.podspec
- Split.xcodeproj/xcshareddata/xcschemes/Split.xcscheme
- Split/Common/Utils/Version.swift
- Split/Network/Streaming/BackoffCounterTimer.swift
- Handling properties in a serial queue
> SDKS-2390: Improved code to avoid issue with backoff timer

- CHANGES.txt
- Split.podspec
- Split/Common/Utils/Version.swift
- Split/FetcherEngine/Recorder/RecorderWorker.swift
- Split/Network/DataParsing/Json.swift
- Split/Network/Streaming/SseClient.swift
- Split/Network/Streaming/Synchronizer.swift
- Split/Storage/CoreDataHelper.swift
- Split/Storage/Events/EventDao.swift
- Split/Storage/Events/PersistentEventsStorage.swift
- Split/Storage/Impressions/ImpressionDao.swift
- SplitTests/Integration/SplitIntegrationTest.swift
- SplitTests/Streaming/SynchronizerTest.swift
- Improved Json parsing and byte count check when checking accumulated data to flush
> SDKS-2451: Performance improvement when pushing data to local storage

- Split.xcodeproj/project.pbxproj
- Split/Api/DefaultSplitFactory.swift
- Split/Api/SplitFactoryHelper.swift
- SplitTests/Storage/DbForTwoDifferentApiKeyTest.swift
- Added  Integration test for multiple api key factory creation
> SDK-2503: Integration test for multiple api key factory creation

- CHANGES.txt
- Split.podspec
- Split.xcodeproj/project.pbxproj
- Split/Common/Utils/Version.swift
- Split/FetcherEngine/Refresh/SplitsSyncHelper.swift
- SplitTests/Integration/InitialCacheTest.swift
- Fixed initial sync and cache check
- Added Integration tests to validate the fix
> SDKS-2524:  Clear cache issue

- Split/Common/ServiceConstants.swift
- Split/FetcherEngine/HttpMySegmentsFetcher.swift
- Split/FetcherEngine/Refresh/BackgroundSyncWorker.swift
- Split/FetcherEngine/Refresh/PeriodicSyncWorker.swift
- Split/FetcherEngine/Refresh/RetryableSyncWorker.swift
- Split/Network/RestClient/RestClient+MySegments.swift
- Split/Network/Streaming/RetryableSplitsUpdateWorkerFactory.swift
- Split/Network/Streaming/SyncUpdateWorker.swift
- Split/Network/Streaming/Synchronizer.swift
- SplitTests/Fake/HttpMySegmentsFetcherStub.swift
- SplitTests/Fake/Network/RestClientStub.swift
- SplitTests/Fake/Streaming/SynchronizerStub.swift
- SplitTests/Fake/SyncWorkerFactoryStub.swift
- SplitTests/MySegmentsSyncWorkerTest.swift
- SplitTests/Service/HttpMySegmentsFetcherTests.swift
- SplitTests/Streaming/SyncUpdateWorkerTest.swift
- Updated my segments sync components to add headers
- Adding no-cache control header when my segments updated notification received
- Updated tests
> SDKS-2589: My segments no cache control header

- Split/Common/ServiceConstants.swift
- SplitTests/MySegmentsSyncWorkerTest.swift
> Fix constant names

- Split.podspec
- Split/Api/SplitApiFacade.swift
- Split/Common/Utils/Version.swift
- Split/FetcherEngine/Refresh/SplitBgSynchronizer.swift
- Split/Network/RestClient/RestClient+SseAuthenticator.swift
- Split/Network/Streaming/PushNotificationManager.swift
- Split/Network/Streaming/SseAuthenticator.swift
- SplitTests/Fake/Streaming/PushNotificationManagerStub.swift
- SplitTests/Streaming/PushNotificationManagerTest.swift
- SplitTests/Streaming/SseAuthenticatorTest.swift
- Parsing jwt only when streaming enabled
- Test updated
> SDKS-2600: JWT fix for streaming disabled

- Split/Network/Endpoints/EndpointFactory.swift
- SplitTests/HttpClient/EndpointFactoryTest.swift
- Fixing endpoints headers and tests
> SDKS-2662: Telem ably metadata

- Split/Metrics/DefaultMetricsManager.swift
- Improved code when updating values to prevent some threading issues
> SDKS-2384: Metrics possible threading race condition

- Split.xcodeproj/project.pbxproj
- Split.xcodeproj/xcshareddata/xcbaselines/592C6AA4211B6C99002D120C.xcbaseline/08F90C28-0C33-4169-9E30-CE7286C05478.plist
- Split.xcodeproj/xcshareddata/xcbaselines/592C6AA4211B6C99002D120C.xcbaseline/Info.plist
- Split/Common/Structs/LRUCache.swift
- Split/Impressions/Impression.swift
- Split/Impressions/ImpressionsObserver.swift
- SplitTests/Impressions/ImpresionsObserverTest.swift
- SplitTests/Impressions/ImpressionHasherTest.swift
- SplitTests/LRUCacheTest.swift
- Added impressions observer, hasher and tests
> SDKS-2811: Impressions observer (imp dedup)

- Split.xcodeproj/project.pbxproj
- Split/Common/Extensions/Date+Utils.swift
- Split/Impressions/ImpressionsCount.swift
- Split/Impressions/ImpressionsCountPerFeature.swift
- Split/Impressions/ImpressionsCounter.swift
- Split/Impressions/ImpressionsObserver.swift
- SplitTests/Impressions/ImpressionsCounterTest.swift
- Added impressions counter and tests
> SDKS-2812: Impressions counter (dedup)

- Split.xcodeproj/project.pbxproj
- Split/Common/ServiceConstants.swift
- Split/Common/Structs/LRUCache.swift
- Split/FetcherEngine/Recorder/ImpressionsCountRecorder.swift
- Split/FetcherEngine/Recorder/ImpressionsCountRecorderWorker.swift
- Split/Impressions/ImpressionsCount.swift
- Split/Impressions/ImpressionsCountPerFeature.swift
- Split/Network/Endpoints/EndpointFactory.swift
- Split/Network/RestClient/RestClient+ImpressionsCount.swift
- Split/Network/RestClient/RestClient.swift
- Split/Storage/Impressions/PersistentImpressionsCountStorage.swift
- SplitTests/Fake/Network/RestClientStub.swift
- SplitTests/Fake/Service/HttpImpressionsCountRecorderStub.swift
- SplitTests/Fake/Storage/PersistentImpressionsCountStorageStub.swift
- SplitTests/Helpers/TestingHelper.swift
- SplitTests/Service/HttpImpressionsCountRecorderTests.swift
- SplitTests/Service/ImpressionsCountRecorderWorkerTests.swift
- Added impressions count recorder, and worker
- Added tests for new components
- Fixed issue in LRU cache
> SDKS-2814: Impressions Counts recorder (imp dedup)

- Split/Api/LocalhostSplitFactory.swift
- Split/Api/SplitClientConfig.swift
- Split/FetcherEngine/Refresh/YamlSplitsStorage.swift
- SplitTests/Fake/SplitEventsManagerMock.swift
- SplitTests/Localhost/LocalhostSplitFetcherTests.swift
- Added multithreading control
- Added new config to handle refresh rate
> SDKS-2891: Fixing issue on localhost returning control when loading splits

- Split.podspec
- Split/Api/DefaultSplitFactory.swift
- Split/Api/LocalhostSplitClient.swift
- Split/Api/LocalhostSplitFactory.swift
- Split/Common/Utils/Version.swift
- Split/FetcherEngine/Refresh/EmptyMySegmentsStorage.swift
- Split/FetcherEngine/Refresh/YamlSplitsStorage.swift
- Split/Storage/MySegments/MySegmentsStorage.swift
- Split/Storage/Splits/SplitsStorage.swift
- SplitTests/Fake/MySegmentsStorageStub.swift
- SplitTests/Fake/SplitEventsManagerMock.swift
- SplitTests/Fake/Storage/SplitsStorageStub.swift
- SplitTests/Localhost/LocalhostManagerTests.swift
- SplitTests/Localhost/LocalhostSplitClientTests.swift
- SplitTests/Localhost/LocalhostSplitFetcherTests.swift
- Renaming localhost storage to a more accurate name
> Localhost storage rename

- Split.xcodeproj/project.pbxproj
- Split/Api/SplitFactoryHelper.swift
- Split/Common/Extensions/Date+Utils.swift
- Split/FetcherEngine/Refresh/YamlSplitsStorage.swift
- Split/Impressions/ImpressionsCount.swift
- Split/Impressions/ImpressionsCountEntity.swift
- Split/Network/Streaming/Synchronizer.swift
- Split/Storage/CoreDataHelper.swift
- Split/Storage/Impressions/ImpressionsCountDao.swift
- Split/Storage/Impressions/PersistentImpressionsCountStorage.swift
- Split/Storage/SplitDatabase.swift
- Split/Storage/split_cache.xcdatamodeld/split_cache.xcdatamodel/contents
- SplitTests/Fake/Storage/ImpressionsCountDaoStub.swift
- SplitTests/Fake/Storage/PersistentImpressionsCountStorageStub.swift
- SplitTests/Fake/Storage/SplitDatabaseStub.swift
- SplitTests/Integration/FetchSpecificSplitsTest.swift
- SplitTests/Integration/SplitChangesServerErrorTest.swift
- SplitTests/Integration/TrackTest.swift
- SplitTests/Service/ImpressionsCountRecorderWorkerTests.swift
- SplitTests/SplitEventsManagerTest.swift
- SplitTests/Storage/ImpressionsCountDaoTests.swift
- SplitTests/Storage/PersistentEventsStorageTest.swift
- SplitTests/Storage/PersistentImpressionsCountStorageTest.swift
- SplitTests/Storage/PersistentImpressionsStorageTest.swift
- SplitTests/Storage/PersistentMySegmentsStorageTests.swift
- SplitTests/Storage/PersistentSplitsStorageTests.swift
- Added impressions count storage components
- Added UT for components
- Improved events manager tests
> SDKS-2815: Save counters on bg

- CHANGES.txt
- Split.podspec
- Split/Common/Utils/Version.swift
- Split/Events/SplitEventsManager.swift
- Split/Network/HttpClient/HttpClient.swift
- Fixing some variables acceded outside the data queue
> SDKS-2912: Fix events manager issue when checking if an event was triggered

- Split.xcodeproj/project.pbxproj
- Split/Common/Extensions/UInt64+bits.swift
- Split/Engine/Hashing/Murmur64x128.swift
- SplitTests/Murmur3HashingTest.swift
- Implemented murmur 64, 128 based on java implementation
- Added set of tests
> SDKS-2992: Murmur64

- Split/Common/Utils/CompressionUtil.swift
- Split/Network/Streaming/SseNotifications.swift
- Added Streaming v2 notification dto
> SDKS-2988: Streaming v2 Notification dto

- Split/Network/Streaming/DefaultSseNotificationParser.swift
- Split/Network/Streaming/SseNotificationProcessor.swift
- Split/Network/Streaming/SseNotifications.swift
- Split/Network/Streaming/SyncManagerBuilder.swift
- Split/Network/Streaming/SyncUpdateWorker.swift
- SplitTests/Fake/Streaming/SseNotificationParserStub.swift
- SplitTests/Fake/Streaming/UpdateWorkerMock.swift
- SplitTests/Streaming/NotificationParserTest.swift
- SplitTests/Streaming/SseNotificationProcessorTest.swift
- SplitTests/Streaming/SyncUpdateWorkerTest.swift
- Added logic to handle unbounded fetch request and tests
> SDKS-2993: Streaming unbounded fetch request handling

- Split/Network/Streaming/SyncUpdateWorker.swift
- SplitTests/Streaming/NotificationParserTest.swift
- SplitTests/Streaming/SyncUpdateWorkerTest.swift
- Added logic to handle segment removal notification and tests
> SDKS-2995: Streaming v2 segment removal

- Split.xcodeproj/project.pbxproj
- Split/Common/Utils/CompressionUtil.swift
- Split/Network/Streaming/DefaultSseNotificationParser.swift
- Split/Network/Streaming/MySegmentsV2PayloadDecoder.swift
- Split/Network/Streaming/SseNotifications.swift
- Split/Network/Streaming/SyncManagerBuilder.swift
- Split/Network/Streaming/SyncUpdateWorker.swift
- SplitTests/Fake/Service/MySegmentsV2PayloadDecoderMock.swift
- SplitTests/Helpers/TestingData.swift
- SplitTests/Streaming/MySegmentsV2PayloaDecoderTest.swift
- SplitTests/Streaming/SseNotificationProcessorTest.swift
- SplitTests/Streaming/SyncUpdateWorkerTest.swift
- Added logic to handle key list notifications and tests
> SDSK-2989 KeyList update strategy (Streaming opt)

- Split/Common/Utils/CompressionUtil.swift
- Split/Network/Streaming/MySegmentsV2PayloadDecoder.swift
- Split/Network/Streaming/SyncUpdateWorker.swift
- SplitTests/Fake/Service/MySegmentsV2PayloadDecoderMock.swift
- SplitTests/Helpers/TestingData.swift
- SplitTests/Streaming/MySegmentsV2PayloaDecoderTest.swift
- SplitTests/Streaming/SseNotificationProcessorTest.swift
- SplitTests/Streaming/SyncUpdateWorkerTest.swift
- Added logic to handle my segments bounded notification and tests 
- Updated buffer size in zlib decompression
> SDKS-2989: My segments v2 Bounded (streaming optimization)-

- Split.xcodeproj/project.pbxproj
- Split/Network/Streaming/MySegmentsV2PayloadDecoder.swift
- Split/Network/Streaming/SseHandler.swift
- Split/Network/Streaming/SseNotificationProcessor.swift
- SplitTests/Fake/Streaming/SynchronizerSpy.swift
- SplitTests/Helpers/TestingData.swift
- SplitTests/Integration/streaming/MySegmentUpdateV2Test.swift
- SplitTests/Resources/push_msg-segment_updV2.txt
- Added integration tests for my segments v2
> SDKS-2996: My segments v2 E2E tests

- Split.xcodeproj/project.pbxproj
- Split/Network/Streaming/MySegmentsV2PayloadDecoder.swift
- Split/Network/Streaming/NotificationManagerKeeper.swift
- Split/Network/Streaming/PushManagerEventBroadcaster.swift
- Split/Network/Streaming/PushNotificationManager.swift
- Split/Network/Streaming/SseNotifications.swift
- Split/Network/Streaming/SyncManager.swift
- Split/Network/Streaming/SyncUpdateWorker.swift
- SplitTests/Fake/BackoffCounterTimerStub.swift
- SplitTests/Fake/Service/MySegmentsV2PayloadDecoderMock.swift
- SplitTests/Fake/Streaming/PushNotificationManagerStub.swift
- SplitTests/Helpers/TestingData.swift
- SplitTests/Integration/streaming/StreamingControlResetTest.swift
- SplitTests/Streaming/MySegmentsV2PayloaDecoderTest.swift
- SplitTests/Streaming/NotificationManagerKeeperTest.swift
- SplitTests/Streaming/SyncManagerTest.swift
- SplitTests/Streaming/SyncUpdateWorkerTest.swift
- Added streaming reset and tests
- Improved payload decoded interface
- Fixed typo in testing data
> SDKS-2983: Streaming (optimization) reset

- Split.xcodeproj/project.pbxproj
- Split/Common/Utils/PeriodicTaskManager.swift
- Split/Network/Endpoints/ServiceEndpoints.swift
- Split/Network/RestClient/RestClient+SseAuthenticator.swift
- Split/Network/Streaming/PushNotificationManager.swift
- Split/Network/Streaming/SseAuthenticator.swift
- SplitTests/Helpers/IntegrationHelper.swift
- SplitTests/Integration/streaming/StreamingDelayTest.swift
- SplitTests/Streaming/PushNotificationManagerTest.swift
- SplitTests/Streaming/SseAuthenticatorTest.swift
- Added streaming delay and tests
> SDKS-2986:  Streaming delay (optimization)

- Split/Common/ServiceConstants.swift
- Split/Network/RestClient/RestClient+SseAuthenticator.swift
- Split/Network/Streaming/SseAuthenticator.swift
- Added default value for streaming connection delay
> Default Streaming conn delay default

- Split.xcodeproj/project.pbxproj
- Split/Common/Extensions/Dictionary+DynamicCodable.swift
- Split/Common/Utils/CastUtils.swift
- Split/Storage/Attributes/AttributeEntity.swift
- Split/Storage/Attributes/AttributeMap.swift
- Split/Storage/Attributes/AttributesDao.swift
- Split/Storage/Attributes/PersistentAttributesStorage.swift
- Split/Storage/CoreDataHelper.swift
- Split/Storage/SplitDatabase.swift
- Split/Storage/split_cache.xcdatamodeld/split_cache_v2.xcdatamodel/contents
- Split/Track/Models/EventDTO.swift
- SplitTests/Fake/Storage/AttributesDaoStub.swift
- SplitTests/Fake/Storage/IntegrationCoreDataHelper.swift
- SplitTests/Fake/Storage/SplitDatabaseStub.swift
- SplitTests/Storage/AttributesDaoTests.swift
- SplitTests/Storage/PersistentAttributesStorageTests.swift
- SplitTests/Storage/PersistentEventsStorageTest.swift
- SplitTests/Storage/PersistentImpressionsCountStorageTest.swift
- SplitTests/Storage/PersistentImpressionsStorageTest.swift
- SplitTests/Storage/PersistentMySegmentsStorageTests.swift
- SplitTests/Storage/PersistentSplitsStorageTests.swift
- Added Persistent Storage attributes
- Added Dao components
- Added tests for new components
- Updated existing tests
> SDKS-5274:  Persistent user attributes storage

- Split.xcodeproj/project.pbxproj
- Split/Storage/Attributes/AttributesStorage.swift
- Split/Storage/MySegments/MySegmentsStorage.swift
- SplitTests/Fake/Storage/PersistentAttributesStorageStub.swift
- SplitTests/Storage/AttributesStorageTests.swift
- Added in memory user attributes storage and tests
> SDKS-5275: In memory attributes storage

- Split.xcodeproj/project.pbxproj
- Split/Common/Structs/SyncDictionarySingleWrapper.swift
- Split/Storage/Attributes/AttributesStorage.swift
- SplitTests/Integration/AttributesEvaluationTest.swift
- SplitTests/Resources/attributes_test_split.json
- SplitTests/Storage/AttributesStorageTests.swift
Updated behavior for set all attributes function in Attributes storage
Updated tests
> SDKS-5276: Updated set attributes function behavior

- Split.xcodeproj/project.pbxproj
- Split/Telemetry/Storage/TelemetryConfig.swift
- Split/Telemetry/Storage/TelemetryStats.swift
- Split/Telemetry/Storage/TelemetryStorage.swift
> SDKS-5356: telemetry models

- CHANGES.txt
- Split.podspec
- Split.xcodeproj/project.pbxproj
- Split/Api/DefaultSplitClient.swift
- Split/Api/SplitClientConfig.swift
- Split/Common/Utils/Version.swift
- Split/Storage/Attributes/AttributesDao.swift
- Split/Storage/Splits/SplitDao.swift
- Split/Storage/split_cache.xcdatamodeld/.xccurrentversion
- Split/Storage/split_cache.xcdatamodeld/split_cache_v3.xcdatamodel/contents
- SplitTests/Fake/Storage/AttributesDaoStub.swift
- SplitTests/Fake/Storage/IntegrationCoreDataHelper.swift
- SplitTests/Fake/Storage/SplitDaoStub.swift
- SplitTests/Helpers/TestingHelper.swift
- SplitTests/Integration/AttributesEvaluationTest.swift
- SplitTests/Integration/ReadyFromCacheTest.swift
> Release 2.12.1

- Split.xcodeproj/project.pbxproj
- Split/Common/Structs/ConcurrentSet.swift
- Split/Common/Structs/SyncDictionaryCollectionWrapper.swift
- Split/Common/Structs/SyncDictionarySingleWrapper.swift
- Split/Common/Structs/SynchronizedArrayWrapper.swift
- Split/Common/Utils/Atomic.swift
- Split/Telemetry/LatencyCounter.swift
- Split/Telemetry/Storage/TelemetryConfig.swift
- Split/Telemetry/Storage/TelemetryInMemoryStorage.swift
- Split/Telemetry/Storage/TelemetryStats.swift
- Split/Telemetry/Storage/TelemetryStorage.swift
- SplitTests/Fake/Network/TelemetryProducerStub.swift
- SplitTests/Fake/Storage/InMemoryTelemetryStorageTest.swift
- SplitTests/MySegmentsSyncWorkerTest.swift
- SplitTests/PeriodicMySegmentsSyncWorkerTest.swift
- SplitTests/Service/HttpMySegmentsFetcherTests.swift
- SplitTests/Service/HttpSplitFetcherTests.swift
- SplitTests/TreatmentManagerTest.swift
- Added In memory telemetry storage component
- Updated models to send data to sdk endpoints
- Improved some storage interfaces
- Added UT for components
> SDKS-5355: Added telemetry storage, necessary dtos and tests

- Split.xcodeproj/project.pbxproj
- Split/Common/Structs/ConcurrentSet.swift
- Split/Common/Structs/SyncDictionaryCollectionWrapper.swift
- Split/Common/Structs/SyncDictionarySingleWrapper.swift
- Split/Common/Structs/SynchronizedArrayWrapper.swift
- Split/Common/Utils/Atomic.swift
- Split/FetcherEngine/Recorder/TelemetryConfigRecorder.swift
- Split/FetcherEngine/Recorder/TelemetryConfigRecorderWorker.swift
- Split/Network/Endpoints/EndpointFactory.swift
- Split/Network/RestClient/RestClient+TelemetryConfig.swift
- Split/Telemetry/LatencyCounter.swift
- Split/Telemetry/Storage/TelemetryConfig.swift
- Split/Telemetry/Storage/TelemetryInMemoryStorage.swift
- Split/Telemetry/Storage/TelemetryStats.swift
- Split/Telemetry/Storage/TelemetryStorage.swift
- SplitTests/Fake/Network/TelemetryProducerStub.swift
- SplitTests/Fake/Service/HttpTelemetryConfigRecorderStub.swift
- SplitTests/Fake/Storage/InMemoryTelemetryStorageTest.swift
- SplitTests/HttpClient/EndpointFactoryTest.swift
- SplitTests/MySegmentsSyncWorkerTest.swift
- SplitTests/PeriodicMySegmentsSyncWorkerTest.swift
- SplitTests/Service/HttpMySegmentsFetcherTests.swift
- SplitTests/Service/HttpSplitFetcherTests.swift
- SplitTests/Service/TelemetryConfigRecorderWorkerTests.swift
- SplitTests/TreatmentManagerTest.swift
- Added telemetry config recorder components and tests
> SDKS-5355: Config recorder

- Split/Telemetry/Storage/TelemetryInMemoryStorage.swift
- Split/Telemetry/Storage/TelemetryStorage.swift
- SplitTests/Fake/Network/TelemetryProducerStub.swift
- SplitTests/Fake/Storage/InMemoryTelemetryStorageTest.swift
- Added some missing method to send telemetry config in storage
- Updated UT
> Adding some missing recorders to complete config sending task

- Split.xcodeproj/project.pbxproj
- Split/Api/DefaultSplitFactory.swift
- Split/Api/DefaultSplitFactoryBuilder.swift
- Split/Api/SplitClientConfig.swift
- Split/Api/SplitComponentFactory.swift
- Split/Api/SplitDatabaseHelper.swift
- Split/Common/Utils/Stopwatch.swift
- Split/Common/Validators/FactoryMonitor.swift
- Split/Engine/DefaultTreatmentManager.swift
- Split/Telemetry/Storage/TelemetryInMemoryStorage.swift
- Split/Telemetry/Storage/TelemetryStorage.swift
- SplitTests/Fake/Network/TelemetryProducerStub.swift
- SplitTests/Fake/Storage/InMemoryTelemetryStorageTest.swift
- SplitTests/Helpers/SplitTestHelper.swift
- SplitTests/Helpers/TestSplitFactory.swift
- SplitTests/Helpers/TestingHelper.swift
- SplitTests/HttpClient/EndpointFactoryTest.swift
- SplitTests/Integration/InitialCacheTest.swift
- SplitTests/Integration/TelemetryTest.swift
- SplitTests/TreatmentManagerTest.swift
- Added telemetry init producer to record data
- Added tests for new components
- Some refactor for config telemetry recorders and components
> SDKS-5362: Init integration producer

- Split/Api/DefaultSplitClient.swift
- Split/Api/SplitClientConfig.swift
- Split/Common/Utils/Stopwatch.swift
- Split/Common/Validators/FactoryMonitor.swift
- Split/Engine/DefaultTreatmentManager.swift
- SplitTests/Integration/TelemetryTest.swift
- Added telemetry evaluation recording calls
- Added integration tests for that calls
> SDKS-5361: Telemetry evaluation producer integration

- Split.xcodeproj/project.pbxproj
- Split/Api/SplitApiFacade.swift
- Split/Api/SplitClientConfig.swift
- Split/Api/SplitComponentFactory.swift
- Split/Api/TelemetryConfigHelper.swift
- Split/Network/Streaming/RetryableSplitsUpdateWorkerFactory.swift
- Split/Network/Sync/Synchronizer.swift
- Split/Network/Sync/TelemetrySynchronizer.swift
- SplitTests/Fake/Streaming/SynchronizerSpy.swift
- SplitTests/Fake/SyncWorkerFactoryStub.swift
- SplitTests/Helpers/TestSplitFactory.swift
- SplitTests/Service/TelemetrySynchronizerTest.swift
- SplitTests/Streaming/SynchronizerTest.swift
- Integrated telemetry synchronizer component
- Tests updated
> SDKS-5365: Telemetry sync integration

- Split/Api/SplitClientConfig.swift
- Split/Api/SplitComponentFactory.swift
- Split/Api/TelemetryConfigHelper.swift
- Split/Network/Streaming/PushNotificationManager.swift
- Split/Telemetry/Storage/TelemetryInMemoryStorage.swift
> SDKS-5366: Manual tests and polishing

- Split.xcodeproj/project.pbxproj
- Split/Api/SplitDatabaseHelper.swift
- Split/FetcherEngine/Refresh/BackgroundSyncWorker.swift
- Split/Storage/MySegments/MySegmentsStorage.swift
- Split/Storage/MySegments/OneKeyPersistentMySegmentsStorage.swift
- Split/Storage/MySegments/PersistentMySegmentsStorage.swift
- SplitTests/Fake/Storage/PersistentMySegmentsStorageStub.swift
- SplitTests/Storage/OneKeyPersistentMySegmentsStorageTests.swift
- Added multi key persisten storage for my segments
- Added tests for new componet
- Deprecated old components
> SDKS-5538: Added new multi key persistent storage

- Split.xcodeproj/project.pbxproj
- Split/Api/SplitDatabaseHelper.swift
- Split/Storage/Attributes/AttributesStorage.swift
- Split/Storage/Attributes/OneKeyPersistentAttributesStorage.swift
- Split/Storage/Attributes/PersistentAttributesStorage.swift
- Split/Storage/MySegments/ByKeyMySegmentsStorage.swift
- Split/Storage/MySegments/OneKeyMySegmentsStorage.swift
- SplitTests/Fake/Storage/OneKeyPersistentAttributesStorageStub.swift
- SplitTests/Fake/Storage/PersistentAttributesStorageStub.swift
- SplitTests/Storage/AttributesStorageTests.swift
- SplitTests/Storage/OneKeyPersistentAttributesStorageTests.swift
- SplitTests/Storage/PersistentAttributesStorageTests.swift
- Added multi key persistent storage for user atrributes
- Added tests for the component
- Deprecated old components
> SDKS-5585: Multikey attributes persistent storage

- Split.xcodeproj/project.pbxproj
- Split/Api/DefaultSplitClient.swift
- Split/Api/SplitDatabaseHelper.swift
- Split/Common/Structs/ConcurrentDictionaryComposed.swift
- Split/Common/Structs/ConcurrentDictionarySet.swift
- Split/Engine/DefaultTreatmentManager.swift
- Split/Network/Sync/Synchronizer.swift
- Split/Storage/Attributes/AttributesStorage.swift
- Split/Storage/Attributes/ByKeyAttributesStorage.swift
- Split/Storage/Attributes/OneKeyAttributesStorage.swift
- Split/Storage/Attributes/PersistentAttributesStorage.swift
- Split/Storage/MySegments/OneKeyMySegmentsStorage.swift
- SplitTests/Fake/Storage/AttributesStorageStub.swift
- SplitTests/Integration/TelemetryTest.swift
- SplitTests/Storage/AttributesStorageTests.swift
- SplitTests/Storage/ByKeyAttributesStorageTests.swift
- SplitTests/Streaming/SynchronizerTest.swift
- SplitTests/TreatmentManagerTest.swift
- Added components to handle multiple key
- Updated one key only storage to work with multi key storage
- Added tests for new components
- Deprecated old components
> SDKS-5586: Added support for multi clients to general attribute storage

- .github/workflows/xcframework.yaml
- CHANGES.txt
- Package.swift
- Split.podspec
- Split.xcodeproj/project.pbxproj
- Split/Common/Utils/Version.swift
> Release 2.13.2

- Split.xcodeproj/project.pbxproj
- Split/Api/DefaultSplitClient.swift
- Split/Api/DefaultSplitFactory.swift
- Split/Api/LocalhostSplitFactory.swift
- Split/Api/SplitClientManager.swift
- Split/Api/SplitFactory.swift
- Split/Common/Structs/KeyStorage.swift
- Split/Engine/Evaluator.swift
- Split/Engine/Splitter.swift
- Split/Events/EventsManagerCoordinator.swift
- Split/Matchers/Whitelist.swift
- Split/Models/Key.swift
- Split/Network/DataParsing/Json.swift
- Split/Network/Streaming/PushNotificationManager.swift
- Split/Network/Sync/MySegmentSynchronizerGroup.swift
- SplitTests/Fake/Service/ByKeyFacadeStub.swift
- SplitTests/Fake/Service/SplitEventsManagerCoordinatorStub.swift
- SplitTests/Fake/SplitFactoryStub.swift
- SplitTests/Integration/MultiClient/BucketSplitTest.swift
- SplitTests/Integration/MultiClient/MultiClientEvaluationTest.swift
- SplitTests/Integration/MultiClient/MultiClientStreamingResetTest.swift
- SplitTests/Resources/Integration/bucket_split_test.json
- SplitTests/Resources/Integration/multi_client_test.json
- SplitTests/SplitClientManagerTest.swift
- SplitTests/SplitEventsCoordinatorTest.swift
- SplitTests/Streaming/ByKeyFacadeTest.swift
- SplitTests/Streaming/PushNotificationManagerTest.swift
- Fixed with bucketing key preventing fire sdk ready trigger when two different bucketing key used with the same matching key
- Improved tests to cover the case
> SDKS-5597: Fix issue with bucketing key in multi client

- Split.xcodeproj/project.pbxproj
- Split/Impressions/ImpressionsCountEntity.swift
- Split/Storage/Attributes/AttributeEntity.swift
- Split/Storage/GeneralInfo/GeneralInfoEntity.swift
- Split/Storage/Impressions/ImpressionEntity.swift
- Split/Storage/MySegments/MySegmentEntity.swift
- Split/Storage/Splits/SplitEntity.swift
- Split/Storage/UniqueKeys/PersistentUniqueKeysStorage.swift
- Split/Storage/UniqueKeys/UniqueKey.swift
- Split/Storage/UniqueKeys/UniqueKeyDao.swift
- Split/Storage/UniqueKeys/UniqueKeyEntity.swift
- Split/Storage/split_cache.xcdatamodeld/split_cache_v3.xcdatamodel/contents
- Split/Storage/split_cache.xcdatamodeld/split_cache_v4.xcdatamodel/contents
- SplitTests/Fake/Storage/UniqueKeyDaoStub.swift
- SplitTests/Storage/PersistentUniqueKeysStorageTests.swift
- SplitTests/Storage/UniqueKeyDaoTests.swift
> SDKS-5797: Adding multi record support to unique key storage

- Split.xcodeproj/project.pbxproj
- Split/Api/SplitClientConfig.swift
- Split/Api/SplitComponentFactory.swift
- Split/Api/SplitDatabaseHelper.swift
- Split/Common/Structs/ConcurrentDictionarySet.swift
- Split/Network/Sync/ImpressionsTracker.swift
- Split/Network/Sync/SyncCommons.swift
- Split/Network/Sync/UniqueKeyTracker.swift
- Split/Storage/Impressions/ImpressionsMode.swift
- Split/Storage/UniqueKeys/PersistentUniqueKeysStorage.swift
- Split/Storage/UniqueKeys/UniqueKey.swift
- Split/Storage/UniqueKeys/UniqueKeyDao.swift
- Split/Storage/UniqueKeys/UniqueKeyEntity.swift
- Split/Storage/split_cache.xcdatamodeld/split_cache_v4.xcdatamodel/contents
- SplitTests/Fake/Storage/PersistentUniqueKeyStorageStub.swift
- SplitTests/Fake/Storage/UniqueKeyTrackerStub.swift
- SplitTests/Helpers/TestSplitFactory.swift
- SplitTests/Storage/PersistentUniqueKeysStorageTests.swift
- SplitTests/Storage/UniqueKeyDaoTests.swift
- SplitTests/Streaming/ImpressionsTrackerTest.swift
- SplitTests/Streaming/SynchronizerTest.swift
- SplitTests/Streaming/UniqueTrackerTest.swift
- SplitTests/TreatmentManagerTest.swift
- Added Unique Key tracker component
- Added test for the component
- Integration on impressions tracker
> SDKS-5798: Unique key tracker

- Split.xcodeproj/project.pbxproj
- Split/Api/SplitClientConfig.swift
- Split/Impressions/UniqueKey.swift
- Split/Impressions/UniqueKeys.swift
- Split/Network/Sync/ImpressionsTracker.swift
- SplitTests/Integration/ImpressionsNoneTest.swift
Added integration tests for impressions mode = NONE
> SDKS-5798: Eval no impressions. Integration tests

- Split/Api/SplitClientConfig.swift
- Split/Network/Sync/MySegmentsSynchronizer.swift
- Split/Network/Sync/SyncManager.swift
- Split/Network/Sync/SyncManagerBuilder.swift
- Split/Network/Sync/Synchronizer.swift
- SplitTests/Streaming/SyncManagerTest.swift
- SplitTests/Streaming/SynchronizerTest.swift
- Updated components to perform only one sync on sdk startup
- updated tests
> SDKS-5898: Performing only one sync on init

- Split.xcodeproj/project.pbxproj
- Split/Api/SplitClientConfig.swift
- Split/FetcherEngine/HttpSplitFetcher.swift
- Split/FetcherEngine/Refresh/BackgroundSyncWorker.swift
- Split/FetcherEngine/Refresh/PeriodicSyncWorker.swift
- Split/FetcherEngine/Refresh/RetryableSyncWorker.swift
- Split/FetcherEngine/Refresh/SplitBgSynchronizer.swift
- Split/FetcherEngine/Refresh/SplitsSyncHelper.swift
- Split/Network/RestClient/RestClient+SplitChanges.swift
- Split/Network/Streaming/ReconnectBackoffCounter.swift
- Split/Network/Streaming/RetryableSplitsUpdateWorkerFactory.swift
- SplitTests/Fake/Network/RestClientStub.swift
- SplitTests/Fake/Service/HttpSplitFetcherStub.swift
- SplitTests/Integration/CdnByPassTest.swift
- SplitTests/PeriodicSplitsSyncWorkerTest.swift
- SplitTests/Service/HttpSplitFetcherTests.swift
- SplitTests/SplitsBgSyncWorkerTest.swift
- SplitTests/SplitsSyncWorkerTest.swift
- SplitTests/SplitsUpdateWorkerTest.swift
- SplitTests/Storage/DbForTwoDifferentApiKeyTest.swift
- Adding CDN by pass patch and tests
> SDKS-5925: CDN Bypass patch

- Split.podspec
- Split/Api/SplitClientConfig.swift
- Split/Common/Utils/Version.swift
- Split/Network/Sync/MySegmentsSynchronizer.swift
- Split/Network/Sync/SyncManager.swift
- Split/Network/Sync/SyncManagerBuilder.swift
- Split/Network/Sync/Synchronizer.swift
- SplitTests/Integration/SingleSyncTest.swift
- SplitTests/Streaming/SyncManagerTest.swift
- SplitTests/Streaming/SynchronizerTest.swift
> SDKS-5898: Single sync config rename

- .github/workflows/update-license-year.yml
> removed workflow from push

- Split.xcodeproj/project.pbxproj
- Split/Api/SplitClientConfig.swift
- Split/Api/SplitDatabaseHelper.swift
- Split/Api/SplitLogLevel.swift
- Split/Common/Structs/ConcurrentDictionaryList.swift
- Split/Common/Structs/LRUCache.swift
- Split/Common/Structs/SynchronizedArrayQueue.swift
- Split/Common/Utils/JFBCrypt/JFBCrypt.h
- Split/Common/Utils/Logger.swift
- Split/Engine/Evaluator.swift
- Split/Events/SplitEventsManager.swift
- Split/FetcherEngine/Recorder/EventsRecorderWorker.swift
- Split/FetcherEngine/Recorder/ImpressionsCountRecorderWorker.swift
- Split/FetcherEngine/Recorder/ImpressionsRecorderWorker.swift
- Split/FetcherEngine/Recorder/UniqueKeysRecorderWorker.swift
- Split/FetcherEngine/Refresh/PeriodicSyncWorker.swift
- Split/FetcherEngine/Refresh/SplitsSyncHelper.swift
- Split/FetcherEngine/Refresh/YamlSplitsStorage.swift
- Split/Network/Streaming/NotificationManagerKeeper.swift
- Split/Network/Sync/SyncManagerBuilder.swift
- SplitTests/Fake/FileStorageStub.swift
- SplitTests/Fake/LogPrinterStub.swift
- SplitTests/Integration/LoggerTest.swift
- SplitTests/Integration/MultiClient/BucketSplitTest.swift
- SplitTests/Integration/SplitIntegrationTest.swift
- SplitTests/Storage/DbForTwoDifferentApiKeyTest.swift
> SDKS-5945: Handling log system by standard levels

- CHANGES.txt
- Split.podspec
- Split/Common/Utils/JFBCrypt/JFBCrypt.h
- Split/Common/Utils/Version.swift
- Fixing issues while building and archiving using SPM
> Release 2.16.1

- Split.podspec
- Split.xcodeproj/project.pbxproj
- Split.xcodeproj/xcshareddata/xcschemes/WatchOS.xcscheme
- Split/Common/Utils/Version.swift
- Split/Common/Utils/framework/HashHelper.swift
- Split/Split.h
- SplitWatchOS/SplitWatchOS.h
- SplitWatchOS/module.modulemap
- Update setup to build all platforms using cocoapods
> SDKS-6130: Cocoapods setup

- Split/Api/DefaultSplitFactory.swift
- Split/Api/SplitComponentFactory.swift
- Split/Common/Utils/NotificationsHelper.swift
- Split/Network/Sync/ImpressionsTracker.swift
- SplitTests/Helpers/TestSplitFactory.swift
- SplitTests/Integration/ImpressionsNoneTest.swift
- SplitTests/Integration/streaming/StreamingDelayTest.swift
- SplitTests/Streaming/ImpressionsTrackerTest.swift
- Saving impressions counts and keys on macos inactive status
- Updated tests
> Fixing some lifecycle issues on macos

- .github/workflows/build_ios.yaml
- CHANGES.txt
- Split.podspec
- Split/Api/SplitClientConfig.swift
- Split/Common/Utils/Version.swift
- Split/Network/Streaming/PushNotificationManager.swift
> Release 2.18.0

- CHANGES.txt
- Split.podspec
- Split/Common/Utils/Version.swift
> Release 2.18.1

- Split.xcodeproj/project.pbxproj
- Split/Api/SplitClientConfig.swift
- Split/Storage/Impressions/ImpressionDao.swift
- Split/Storage/Impressions/ImpressionsMode.swift
- Split/Storage/Impressions/ImpressionsStorage.swift
- Split/Storage/Impressions/PersistentImpressionsStorage.swift
- SplitTests/Collections/BlockingQueueTest.swift
- SplitTests/Fake/Storage/ImpressionDaoStub.swift
- SplitTests/Fake/Storage/PersistentImpressionsStorageStub.swift
- SplitTests/Integration/MultiClient/MultiClientEvaluationTest.swift
- SplitTests/Storage/ImpressionDaoTests.swift
- SplitTests/Storage/ImpressionsStorageTest.swift
- SplitTests/Storage/PersistentImpressionsStorageTest.swift
- Created in memory impressions storage and tests
> SDKS-6333: Impressions in memory storage

- Split.xcodeproj/project.pbxproj
- Split/Api/EventsTracker.swift
- Split/Network/Sync/ImpressionsTracker.swift
- SplitTests/Fake/AnyValueValidatorStub.swift
- SplitTests/Fake/EventValidatorStub.swift
- SplitTests/Fake/Storage/PersistentImpressionsCountStorageStub.swift
- SplitTests/Fake/Streaming/ImpressionsTrackerStub.swift
- SplitTests/Streaming/EventsTrackerTest.swift
- SplitTests/Streaming/ImpressionsTrackerTest.swift
- Added flag and logic to start / stop impressions and events tracking
- Added tests for the feature
- Improved some existing tests
> SDkS-6292: User consent enable / disable tracking

- Split.xcodeproj/project.pbxproj
- Split/Api/SplitComponentFactory.swift
- Split/Network/Sync/EventsSynchronizer.swift
- Split/Network/Sync/SyncManager.swift
- Split/Network/Sync/Synchronizer.swift
- SplitTests/Fake/Service/EventsSynchronizerStub.swift
- SplitTests/Fake/Service/TelemetrySynchronizerStub.swift
- SplitTests/Fake/Streaming/SynchronizerSpy.swift
- SplitTests/Fake/Streaming/SynchronizerStub.swift
- SplitTests/Helpers/TestSplitFactory.swift
- SplitTests/Streaming/EventsSynchronizerTest.swift
- SplitTests/Streaming/SyncManagerTest.swift
- SplitTests/Streaming/SynchronizerTest.swift
- Added logic to start / top recording events and impressions when needed
- Refactored events synchronizing logic
- Added tests for new logic and components
> SDKS-6293: User consent start / stop recording

- Split.xcodeproj/project.pbxproj
- Split/Api/DefaultSplitFactory.swift
- Split/Api/SplitClientManager.swift
- Split/Api/SplitComponentFactory.swift
- Split/Api/UserConsentManager.swift
- Split/FetcherEngine/Recorder/EventsRecorderWorker.swift
- Split/FetcherEngine/Recorder/ImpressionsRecorderWorker.swift
- Split/FetcherEngine/Recorder/RecorderWorker.swift
- Split/Impressions/ImpressionsCounter.swift
- Split/Impressions/ImpressionsObserver.swift
- Split/Network/Sync/ImpressionsTracker.swift
- Split/Network/Sync/UniqueKeyTracker.swift
- SplitTests/Fake/Storage/ImpressionsStorageStub.swift
- SplitTests/Fake/Storage/UniqueKeyTrackerStub.swift
- SplitTests/Fake/Streaming/ImpressionsTrackerStub.swift
- SplitTests/Helpers/TestSplitFactory.swift
- SplitTests/Integration/UserConsent/UserConsentModeDebugTest.swift
- SplitTests/Integration/UserConsent/UserConsentModeNoneTest.swift
- SplitTests/Integration/UserConsent/UserConsentModeOptimizedTest.swift
- SplitTests/Integration/UserConsent/UserConsentTest.swift
- SplitTests/Streaming/EventsSynchronizerTest.swift
- SplitTests/Streaming/ImpressionsTrackerTest.swift
- SplitTests/UserConsentManagerTest.swift
- Fixed some issues in user consent management logic
- Some improvements added too
- Integration tests for all impressions modes and events
> SDKS-6296: User consent integration tests

- Split/Storage/Splits/SplitsDecoder.swift
- Split/Storage/Splits/SplitsEncoder.swift
- Some logs removed
- Limiting operation queue threads
> SDKS-6454: Parallel parsing adjustments

- .github/workflows/test_ios_integration.yaml
- .github/workflows/test_ios_streaming.yaml
- .github/workflows/test_ios_ut.yaml
- SplitTests/Integration/UserConsent/UserConsentModeOptimizedTest.swift
> Fix sonar jre issue

- Split.xcodeproj/project.pbxproj
- Split/Api/SplitClientConfig.swift
- Split/Api/SplitComponentFactory.swift
- Split/Api/SplitDatabaseHelper.swift
- Split/Api/SplitEncryptionLevel.swift
- Split/Common/Utils/DbCipher.swift
- Split/FetcherEngine/Refresh/SplitBgSynchronizer.swift
- Split/Network/Errors/GenericError.swift
- Split/Storage/Splits/SplitDao.swift
- SplitTests/DbCipherTest.swift
- SplitTests/Helpers/TestSplitFactory.swift
- SplitTests/Helpers/TestingHelper.swift
- SplitTests/SplitClientManagerTest.swift
- Added component to encrypt / decrypt that db
- Tests
> SDKS-6626: Created cipher for the whole db

- Split.xcodeproj/project.pbxproj
- Split/Api/SplitClientConfig.swift
- Split/Api/SplitDatabaseHelper.swift
- Split/Common/Extensions/String+Utils.swift
- Split/Common/Utils/Base64Utils.swift
- Split/Common/Utils/Cipher.swift
- Split/Common/Utils/DbCipher.swift
- Split/FetcherEngine/Refresh/SplitBgSynchronizer.swift
- Split/Storage/Global/GlobalSecureStorage.swift
- Split/Storage/Global/KeyValueStorage.swift
- SplitTests/CipherTest.swift
- SplitTests/DbCipherTest.swift
- SplitTests/Fake/Storage/SecureStorageStub.swift
- SplitTests/Helpers/IntegrationHelper.swift
- SplitTests/InitDbCipherTest.swift
- SplitTests/Integration/ReadyFromCacheTest.swift
- SplitTests/KeyGeneratorTest.swift
- SplitTests/Storage/AttributesDaoTest.swift
- SplitTests/Storage/EventDaoTest.swift
- SplitTests/Storage/ImpressionDaoTest.swift
- SplitTests/Storage/ImpressionsCountDaoTest.swift
- SplitTests/Storage/MySegmentsDaoTest.swift
- SplitTests/Storage/SplitDaoTest.swift
- SplitTests/Storage/UniqueKeyDaoTest.swift
- Created random key generator for encryption
- Using random key for encryption
- Test updated and improved
> SDKS-6556: Encryption key generator

- CHANGES.txt
- README.md
Replaced 'split' by 'feature flag'
> SDKS-6904: Readme and changelog split replacement

- Split.xcodeproj/project.pbxproj
- Split/FetcherEngine/Recorder/TelemetryStatsRecorderWorker.swift
- Split/Network/Streaming/SyncUpdateWorker.swift
- Split/Network/Sync/SyncManagerBuilder.swift
- Split/Telemetry/Storage/TelemetryInMemoryStorage.swift
- Split/Telemetry/Storage/TelemetryStats.swift
- Split/Telemetry/Storage/TelemetryStorage.swift
- SplitTests/Fake/Network/TelemetryProducerStub.swift
- SplitTests/Fake/Service/FeatureFlagsPayloadDecoderMock.swift
- SplitTests/Fake/Service/SplitChangeProcessorStub.swift
- SplitTests/Fake/Storage/InMemoryTelemetryStorageTest.swift
- SplitTests/Fake/Storage/SplitsStorageStub.swift
- SplitTests/Fake/Streaming/DecompressionMocks.swift
- SplitTests/Helpers/TestingHelper.swift
- SplitTests/Service/Telemetry/TelemetryStatsRecorderWorkerTests.swift
- SplitTests/Streaming/SseNotificationProcessorTest.swift
- SplitTests/Streaming/SyncUpdateWorkerTest.swift
- Update feature flag streaming worker to handle this new updating way
- Test for the new feature
- Added Telemetry to workers. Updated tests.
> SDKS-7150: Instant feature flags update

- Split.xcodeproj/project.pbxproj
- Split/Network/Streaming/DefaultSseNotificationParser.swift
- Split/Network/Streaming/SyncUpdateWorker.swift
- Split/Network/Sync/FeatureFlagsSynchronizer.swift
- Split/Network/Sync/MySegmentsSynchronizer.swift
- Split/Network/Sync/Synchronizer.swift
- SplitTests/Fake/Streaming/FeatureFlagsSynchronizerStub.swift
- SplitTests/Fake/Streaming/SynchronizerSpy.swift
- SplitTests/Fake/Streaming/SynchronizerStub.swift
- SplitTests/Helpers/TestingData.swift
- SplitTests/Integration/streaming/InstantFeatureFlagsUpdateTest.swift
- Triggering  sdk_udpated event when IFFU
- Added integration tests
> SDKS-7151: Instant feature flags update integration tests

- Split.xcodeproj/project.pbxproj
- Split/Api/FilterBuilder.swift
- Split/Api/FlagSetValidator.swift
- Split/Api/SplitFilter.swift
- Split/Api/SyncConfig.swift
- SplitTests/SplitFilter/FilterBuilderTest.swift
- SplitTests/SplitFilter/FlagSetValidatorTests.swift
- Added flagsets config
- Added flagsets validator
- Tests for new components
> SDKS-7426: Flag sets config and validation

- Split/Models/SplitModel/Split.swift
- Split/Network/Sync/FeatureFlagsSynchronizer.swift
- SplitTests/Fake/Storage/PersistentSplitsStorageStub.swift
- SplitTests/Helpers/TestingHelper.swift
- SplitTests/Streaming/FeatureFlagsSynchronizerTest.swift
- Updated logic when loading feature flags from cache to take into account Sets
- Added UT
> SDKS-7427: Load flagset cache logic

- Split/Api/DefaultSplitClient.swift
- Split/Api/DefaultSplitManager.swift
- Split/Api/FailHelpers.swift
- Split/Api/FlagSetsValidator.swift
- Split/Api/LocalhostSplitClient.swift
- Split/Api/SplitClient.swift
- Split/Api/SplitView.swift
- Split/Engine/DefaultTreatmentManager.swift
- Split/Storage/Splits/FlagSetsCache.swift
- Split/Storage/Splits/SplitsStorage.swift
- SplitTests/Fake/InternalSplitClientStub.swift
- SplitTests/Fake/SplitClientStub.swift
- SplitTests/Integration/Api/FlagSetsIntegrationTest.swift
- SplitTests/Resources/splits.json
- SplitTests/SplitFilter/FlagSetValidatorTests.swift
- SplitTests/SplitManagerTest.swift
- Added sets field to SplitView
- Renamed sets evaluation methods
> SDKS-7431 adjustments

- Split/Api/FlagSetsValidator.swift
- Split/Engine/DefaultTreatmentManager.swift
- SplitTests/Fake/Storage/FlagSetsCacheMock.swift
- SplitTests/Integration/Api/FlagSetsIntegrationTest.swift
- Added feature flag name in SDK ready validation
> SDKS-7628: Split name SDK ready in validation

- Split/Api/DefaultSplitManager.swift
- Split/Api/SplitView.swift
- SplitTests/SplitManagerTest.swift
- Added default treatment to SplitView
> SDKS-7637: Default treatment in SplitView

- Split.xcodeproj/project.pbxproj
- Split.xcodeproj/xcshareddata/xcschemes/Split.xcscheme
- Split/Api/DefaultSplitFactoryBuilder.swift
- Split/Network/Endpoints/ServiceEndpoints.swift
- SplitTests/HttpClient/ServiceEndpointsTests.swift
- SplitTests/Integration/Api/DestroyTest.swift
- SplitTests/Integration/Api/SplitIntegrationTest.swift
- SplitTests/Integration/Recorder/FlushTest.swift
- SplitTests/Integration/Recorder/TrackTest.swift
- SplitTests/Integration/Sync/FetchSpecificSplitsTest.swift
- SplitTests/Integration/Sync/MySegmentServerErrorTest.swift
- SplitTests/Integration/Sync/MySegmentUpadatedTest.swift
- SplitTests/Integration/Sync/SplitChangesServerErrorTest.swift
- SplitTests/Integration/Sync/SplitChangesTest.swift
- SplitTests/Integration/Sync/SplitSdkUpdatePollingTest.swift
- Now, the SDK build process fail if any custom endpoint set is wrong.
> SDKS-7883: Service endpoints new validation logic

- Split.podspec
- Split/Common/Utils/Version.swift
> Version 2.24.1

- CHANGES.txt
- Split.podspec
- Split/Common/Utils/Version.swift
- Split/Network/Streaming/SyncUpdateWorker.swift
- SplitTests/Helpers/TestingData.swift
- SplitTests/Integration/Api/FlagSetsIntegrationTest.swift
- SplitTests/Integration/streaming/InstantFeatureFlagsUpdateTest.swift
- Added previous change number check in split notification worker
> Fix previous cn

- Split/Network/Endpoints/ServiceEndpoints.swift
- Split/Network/Streaming/SyncUpdateWorker.swift
- Split/Storage/split_cache.xcdatamodeld/split_cache_v4.xcdatamodel/contents
- Allowing service endpoints be accessed, necessary from iOS Suite
> Allowing service endpoints be accessed

- Split.podspec
- Split/Common/Utils/Version.swift
> Version 2.24.3-rc1

- .github/workflows/build_macos.yaml
- Split/Network/Endpoints/ServiceEndpoints.swift
- Handling new iOS 17+ URL encondig
> Handling new URL parsing for iOS 17+

- Split/Common/Extensions/Date+Utils.swift
> SDKS-8060: Date extension improvement

- CHANGES.txt
- Split.podspec
- Split.xcodeproj/project.pbxproj
- Split/Api/DefaultSplitClient.swift
- Split/Common/Utils/Version.swift
- Split/Network/Streaming/SyncUpdateWorker.swift
- SplitTests/Fake/ClientManagerMock.swift
- SplitTests/Fake/SplitEventsManagerMock.swift
- SplitTests/Fake/SplitEventsManagerStub.swift
- SplitTests/Fake/TreatmentManagerMock.swift
- SplitTests/Helpers/StreamingTestingHelper.swift
- SplitTests/Helpers/TestingHelper.swift
- SplitTests/Init/SplitClientTests.swift
- SplitTests/Integration/Api/FlagSetsIntegrationTest.swift
- SplitTests/SplitClientManagerTest.swift
- Fixed issues when triggering SDK events
> Release 2.24.6

- Split.xcodeproj/project.pbxproj
- Split/Common/Utils/SplitHelper.swift
- Split/Storage/Splits/SplitsStorage.swift
- SplitTests/Helpers/SplitTestHelper.swift
- SplitTests/Resources/split_unsupported_matcher.json
- SplitTests/Storage/SplitsStorageTests.swift
- Added default condition replacement for feature flags with an unsupported matcher type.
> Default condition

- Split.xcodeproj/project.pbxproj
- Split/Network/HttpClient/HttpClient.swift
- Split/Network/HttpClient/HttpParameters.swift
- Split/Network/HttpClient/HttpRequest.swift
- Split/Network/RestClient/RestClient+SplitChanges.swift
- Split/Network/RestClient/RestClient.swift
- Split/Network/Streaming/SseClient.swift
- SplitTests/Fake/Network/HttpClientMock.swift
- SplitTests/HttpClient/HttpDataRequestTest.swift
- Added functionality to specify a query param order.
- Added ordering for `splitChanges`
> Query param ordering

- Split.xcodeproj/project.pbxproj
- Split/Common/Utils/Spec.swift
- Split/Common/Utils/Version.swift
- Split/Network/HttpClient/HttpParameter.swift
- Split/Network/HttpClient/HttpParameters.swift
- Split/Network/RestClient/RestClient+SplitChanges.swift
- Split/Network/RestClient/RestClient+SseAuthenticator.swift
- SplitTests/HttpClient/HttpClientTest.swift
- SplitTests/HttpClient/HttpDataRequestTest.swift
- SplitTests/Integration/Api/FlagSetsIntegrationTest.swift
- SplitTests/Integration/Sync/CdnByPassTest.swift
- SplitTests/Integration/streaming/StreamingInitTest.swift
- Added `Spec` file with `flagsSpec` value.
- Added `s` query parameter to `splitChanges` & `auth` requests.
- Refactored `HttpParameters`.
> Flags spec value

- Split.xcodeproj/project.pbxproj
- Split/Matchers/Semver/BetweenSemverMatcher.swift
- Split/Matchers/Semver/EqualToSemverMatcher.swift
- Split/Models/Matcher.swift
- Split/Models/MatcherType.swift
- SplitTests/Matcher/EqualToSemverMatcherTest.swift
- Added `EqualToSemverMatcher` implementation
> EqualToSemver matcher

- Split.xcodeproj/project.pbxproj
- Split/Matchers/Semver/InListSemverMatcher.swift
- Split/Matchers/Semver/Semver.swift
- Split/Models/Matcher.swift
- Split/Models/MatcherType.swift
- SplitTests/Matcher/EqualToSemverMatcherTest.swift
- SplitTests/Matcher/InListSemverMatcherTest.swift
- Added `InListSemverMatcher` implementation.
> InListSemver matcher

- Split.xcodeproj/project.pbxproj
- Split/Matchers/Semver/GreaterThanOrEqualToSemverMatcher.swift
- Split/Matchers/Semver/LessThanOrEqualToSemverMatcher.swift
- Split/Models/Matcher.swift
- Split/Models/MatcherType.swift
- SplitTests/Matcher/GreaterThanOrEqualToSemverMatcherTest.swift
- SplitTests/Matcher/LessThanOrEqualToSemverMatcherTest.swift
- Added `GreaterThanOrEqualToSemverMatcher` implementation.
- Added `LessThanOrEqualToSemverMatcher` implementation.
> Greater or equal & less or equal semver matchers

- Split.xcodeproj/project.pbxproj
- SplitTests/Integration/Api/SemverIntegrationTest.swift
- SplitTests/Resources/split_changes_semver.json
- Added integration tests for Semver matchers.
> Semver integration tests

- Split.xcodeproj/project.pbxproj
- Split/Common/Utils/SplitHelper.swift
- Split/Impressions/ImpressionsConstants.swift
- Split/Storage/Splits/SplitsStorage.swift
- SplitTests/Integration/Api/UnsupportedMatcherIntegrationTest.swift
- SplitTests/Resources/splitchanges_unsupported.json
- Added integration tests for unsupported matcher.
> Unsupported matcher integration tests

- Split.xcodeproj/project.pbxproj
- Split/Common/ServiceConstants.swift
- Split/Impressions/HashedImpression.swift
- Split/Storage/CoreDataHelper.swift
- Split/Storage/HashedImpression/HashedImpressionDao.swift
- Split/Storage/HashedImpression/HashedImpressionEntity.swift
- Split/Storage/SplitDatabase.swift
- Split/Storage/split_cache.xcdatamodeld/split_cache_v4.xcdatamodel/contents
- SplitTests/Fake/Storage/HashedImpressionDaoMock.swift
- SplitTests/Fake/Storage/SplitDatabaseStub.swift
- SplitTests/Storage/HashedImpressionDaoTest.swift
- SplitTests/Storage/PersistentAttributesStorageTests.swift
- SplitTests/Storage/PersistentEventsStorageTest.swift
- SplitTests/Storage/PersistentImpressionsCountStorageTest.swift
- SplitTests/Storage/PersistentImpressionsStorageTest.swift
- SplitTests/Storage/PersistentMySegmentsStorageTests.swift
- SplitTests/Storage/PersistentSplitsStorageTests.swift
- SplitTests/Storage/PersistentUniqueKeysStorageTests.swift
- Added persistent storage for Hashed impressions
> Created HashedImpression Dao and DB

- Split.xcodeproj/project.pbxproj
- Split/Storage/HashedImpression/PersistentHashedImpressionStorage.swift
- SplitTests/Helpers/SplitTestHelper.swift
- SplitTests/Storage/HashedImpressionDaoTest.swift
- SplitTests/Storage/PersistentHashedImpressionsStorageTest.swift
- Added Hashed impressions persistent storage and tests
> SDKS-8398: Adding persistent hashed storage

- Split.xcodeproj/project.pbxproj
- Split/Api/SplitDatabaseHelper.swift
- Split/Common/ServiceConstants.swift
- Split/Common/Structs/LRUCache.swift
- Split/Impressions/HashedImpression.swift
- Split/Impressions/ImpressionsObserver.swift
- Split/Network/Sync/ImpressionsTracker.swift
- Split/Network/Sync/SyncCommons.swift
- Split/Storage/CoreDataHelper.swift
- Split/Storage/HashedImpression/HashedImpressionDao.swift
- Split/Storage/HashedImpression/HashedImpressionEntity.swift
- Split/Storage/HashedImpression/HashedImpressionStorage.swift
- Split/Storage/HashedImpression/PersistentHashedImpressionsStorage.swift
- Split/Storage/split_cache.xcdatamodeld/split_cache_v4.xcdatamodel/contents
- SplitTests/Fake/Storage/HashedImpressionDaoMock.swift
- SplitTests/Fake/Storage/HashedImpressionsStorageMock.swift
- SplitTests/Fake/Storage/PersistentHashImpressionStorageMock.swift
- SplitTests/Helpers/SplitTestHelper.swift
- SplitTests/Helpers/TestingHelper.swift
- SplitTests/Impressions/ImpresionsObserverTest.swift
- SplitTests/Storage/HashedImpressionDaoTest.swift
- SplitTests/Storage/HashedImpressionsStorageTest.swift
- SplitTests/Storage/PersistentHashedImpressionsStorageTest.swift
- SplitTests/Streaming/FeatureFlagsSynchronizerTest.swift
- SplitTests/Streaming/ImpressionsTrackerTest.swift
- SplitTests/Streaming/SynchronizerTest.swift
- SplitTests/TreatmentManagerTest.swift
- Added Hashed impression coordination storage and tests
- Updated old tests and mocks created
> SDKS-8400: Added Hashed impressions storage

- Split/Api/CertificatePinningConfig.swift
- Split/Api/DefaultSplitFactory.swift
- Split/FetcherEngine/Refresh/RetryableSyncWorker.swift
- Split/Network/HttpClient/HttpClient.swift
- Split/Network/HttpClient/HttpRequestList.swift
- Split/Network/HttpClient/HttpRequestManager.swift
- Split/Network/Security/TlsPinChecker.swift
Improved pin checker integration. Avoiding retries for Splits when validation fails #2
> SDKS-8420: Pin checker integration #2 and bugfixing

- Split/Common/Utils/NotificationsHelper.swift
- Split/FetcherEngine/Refresh/PeriodicSyncWorker.swift
- Split/FetcherEngine/Refresh/RetryableSyncWorker.swift
- Split/Localhost/LocalhostClientManager.swift
- Split/Localhost/LocalhostSynchronizer.swift
- Split/Network/HttpClient/HttpClient.swift
- Split/Network/HttpClient/HttpRequestManager.swift
- Split/Network/Sync/ByKeyFacade.swift
- Split/Network/Sync/FeatureFlagsSynchronizer.swift
- Split/Network/Sync/ImpressionsTracker.swift
- Split/Network/Sync/MySegmentsSynchronizer.swift
- Split/Network/Sync/SyncManager.swift
- Split/Network/Sync/Synchronizer.swift
Using a centralized notification system to inform about banned hosts and take appropriate action.
> SDKS-8509: Credential pinning integration #3

- Split.xcodeproj/project.pbxproj
- Split/Common/Utils/NotificationsHelper.swift
- Split/Network/Security/TlsPinChecker.swift
- Split/Network/Sync/ImpressionsTracker.swift
- Split/Network/Sync/SyncManager.swift
- SplitTests/Fake/Network/HttpRequestMock.swift
- SplitTests/Fake/Network/HttpStreamRequestMock.swift
- SplitTests/Fake/Service/ByKeyFacadeStub.swift
- SplitTests/Fake/Service/NotificationHelperStub.swift
- SplitTests/Fake/Service/TlsPinCheckerMock.swift
- SplitTests/Fake/Streaming/FeatureFlagsSynchronizerStub.swift
- SplitTests/Fake/Streaming/ImpressionsTrackerStub.swift
- SplitTests/Fake/Streaming/SynchronizerSpy.swift
- SplitTests/Fake/Streaming/SynchronizerStub.swift
- SplitTests/Helpers/SecurityHelper.swift
- SplitTests/HttpClient/CertPinning/HttpRequestManagerTests.swift
- SplitTests/HttpClient/CertPinning/TlsPinningCheckerTests.swift
- SplitTests/HttpClient/HttpClientTest.swift
- SplitTests/Localhost/LocalhostSynchronizerTests.swift
- SplitTests/Service/MySegments/MySegmentsBgSyncWorkerTest.swift
- SplitTests/Service/Splits/SplitsBgSyncWorkerTest.swift
- SplitTests/Streaming/FeatureFlagsSynchronizerTest.swift
- SplitTests/Streaming/ImpressionsTrackerTest.swift
- SplitTests/Streaming/SseAuthenticatorTest.swift
- SplitTests/Streaming/SyncManagerTest.swift
- SplitTests/Streaming/SynchronizerTest.swift
- Updated. tests to support new protocols and components
> SDK-8509: Test compilation update

- Split/Network/HttpClient/HttpClient.swift
- Split/Network/Security/TlsPinChecker.swift
- Split/Network/Sync/SyncManager.swift
- Split/Network/Sync/SyncManagerBuilder.swift
> SDKS-8509: Cerfificate pinning final adjustments and logging

- Split/Api/CertificatePinningConfig.swift
- Split/Api/DefaultSplitFactory.swift
- Split/FetcherEngine/Refresh/SplitBgSynchronizer.swift
- Split/Network/Security/TlsPinChecker.swift
- Split/Storage/Global/KeyValueStorage.swift
- SplitTests/Service/Telemetry/TelemetryConfigRecorderWorkerTests.swift
- Added Failure listener and BG sync pins
> SDKS-8420: Failure handler and BG sync

- Split.xcodeproj/project.pbxproj
- Split/Storage/CoreDataHelper.swift
- Split/Storage/MySegments/MySegmentsDao.swift
- Split/Storage/SplitDatabase.swift
- Split/Storage/split_cache.xcdatamodeld/.xccurrentversion
- Split/Storage/split_cache.xcdatamodeld/split_cache_v5.xcdatamodel/contents
- SplitTests/Storage/MySegmentsDaoTest.swift
- Persistent storage for large segments
> SDKS-8662: My Large segments persistent storage

- Split/Telemetry/Storage/TelemetryConfig.swift
- Split/Telemetry/Storage/TelemetryStats.swift
- Split/Telemetry/Storage/TelemetryStorage.swift
- Added large segments values to telemetry structs
> SDKS-8664: Added large segments telemetry values

- Split.xcodeproj/project.pbxproj
- Split/Api/SplitClientConfig.swift
- Split/FetcherEngine/Recorder/TelemetryConfigRecorderWorker.swift
- Split/Network/Endpoints/EndpointFactory.swift
- Split/Network/RestClient/RestClient+MyLargeSegments.swift
- Split/Network/Results/MyLargeSegmentsChange.swift
- Split/Telemetry/Storage/TelemetryConfig.swift
- SplitTests/Helpers/TestingHelper.swift
- SplitTests/HttpClient/EndpointFactoryTest.swift
- SplitTests/Service/Telemetry/TelemetryConfigRecorderWorkerTests.swift
- Added fetcher and supported configs
> SDKS-8664: Large segments fetcher 

- Split.xcodeproj/project.pbxproj
- Split/Api/SplitApiFacade.swift
- Split/Common/Extensions/Set+Extension.swift
- Split/FetcherEngine/HttpMySegmentsFetcher.swift
- Split/FetcherEngine/Refresh/BackgroundSyncWorker.swift
- Split/FetcherEngine/Refresh/ChangesChecker.swift
- Split/FetcherEngine/Refresh/PeriodicSyncWorker.swift
- Split/FetcherEngine/Refresh/RetryableSyncWorker.swift
- Split/FetcherEngine/Refresh/SplitBgSynchronizer.swift
- Split/Network/RestClient/RestClient+MyLargeSegments.swift
- Split/Network/RestClient/RestClient+MySegments.swift
- Split/Network/Results/SegmentsChange.swift
- Split/Network/Streaming/SyncUpdateWorker.swift
> SDKS-8664 - Added my large segments rest client and fetcher

- Split/Storage/MySegments/ByKeyMySegmentsStorage.swift
- Split/Storage/MySegments/MyLargeSegmentEntity.swift
- Split/Storage/MySegments/MyLargeSegmentsDao.swift
- Split/Storage/MySegments/MyLargeSegmentsStorage.swift
- Split/Storage/MySegments/MySegmentsDao.swift
- Split/Storage/MySegments/PersistentMyLargeSegmentsStorage.swift
- Split/Storage/SplitDatabase.swift
- Split/Storage/split_cache.xcdatamodeld/split_cache_v5.xcdatamodel/contents
- SplitTests/Storage/MySegmentsDaoTest.swift
- Added my large segments storage components
- Updated my segments storage API
> SDKS-8661: My large segments storage components

- Split.xcodeproj/project.pbxproj
- Split/FetcherEngine/Refresh/ChangesChecker.swift
- Split/FetcherEngine/Refresh/EmptyMySegmentsStorage.swift
- Split/FetcherEngine/Refresh/PeriodicSyncWorker.swift
- Split/FetcherEngine/Refresh/RetryableSyncWorker.swift
- Split/Network/Results/SegmentsChange.swift
- Split/Network/Streaming/SyncUpdateWorker.swift
Updated my segments fetcher to use the new API storage that is compatible with my Large segments
> SDKS-8406: Updated MS Fetchers

- SplitTests/EvaluatorTests.swift
- SplitTests/Fake/ByKeyMySegmentsStorageStub.swift
- SplitTests/Fake/HttpMySegmentsFetcherStub.swift
- SplitTests/Fake/Network/MySegmentsRetrieverMock.swift
- SplitTests/Fake/Network/RestClientStub.swift
- SplitTests/Fake/Service/ChangesCheckerMock.swift
- SplitTests/Fake/Storage/MyLargeSegmentsDaoStub.swift
- SplitTests/Fake/Storage/MySegmentsStorageStub.swift
- SplitTests/Fake/Storage/SplitDatabaseStub.swift
- SplitTests/Service/MySegments/HttpMySegmentsFetcherTest.swift
- SplitTests/Service/MySegments/MySegmentsBgSyncWorkerTest.swift
- SplitTests/Service/MySegments/MySegmentsChangeChecker.swift
- SplitTests/Service/MySegments/MySegmentsSyncWorkerTest.swift
- SplitTests/Storage/ByKeyMySegmentsStorageTests.swift
- SplitTests/Storage/MyLargeSegmentsDaoTest.swift
- SplitTests/Storage/MySegmentsStorageTests.swift
- SplitTests/Storage/PersistentAttributesStorageTests.swift
- SplitTests/Storage/PersistentEventsStorageTest.swift
- SplitTests/Storage/PersistentHashedImpressionsStorageTest.swift
- SplitTests/Storage/PersistentImpressionsCountStorageTest.swift
- SplitTests/Storage/PersistentImpressionsStorageTest.swift
- SplitTests/Storage/PersistentMySegmentsStorageTests.swift
- SplitTests/Storage/PersistentSplitsStorageTests.swift
- SplitTests/Storage/PersistentUniqueKeysStorageTests.swift
- SplitTests/TreatmentManagerTest.swift
- Tests updated with the new MS API
> SDKS-8661: ls storage #3

- Split.xcodeproj/project.pbxproj
- Split/Api/SplitApiFacade.swift
- Split/Api/SplitDatabaseHelper.swift
- Split/Events/SplitEventsManager.swift
- Split/Events/SplitEventsManagerWrapper.swift
- Split/Events/SplitInternalEvent.swift
- Split/FetcherEngine/Refresh/PeriodicSyncWorker.swift
- Split/Initialization/SplitComponentFactory.swift
- Split/Network/Streaming/RetryableSplitsUpdateWorkerFactory.swift
- Split/Network/Sync/SyncCommons.swift
- Basic MLS storage and fetcher initialization
> SDKS-8661: Basic components init with  MLS storage and fetcher and fetcher

- Split/Api/DefaultSplitFactory.swift
- Split/Api/SplitClientManager.swift
- Split/Events/SplitEventsManager.swift
- Split/Events/SplitEventsManagerWrapper.swift
- Split/FetcherEngine/Refresh/RetryableSyncWorker.swift
- Split/Network/Streaming/RetryableSplitsUpdateWorkerFactory.swift
- Split/Network/Sync/ByKeyFacade.swift
- Split/Network/Sync/MySegmentsSynchronizer.swift
> SDKS-8661: Wiring components to multi client module

- SplitTests/Fake/MySegmentsSyncWorkerFactoryStub.swift
- SplitTests/Fake/Service/ByKeyFacadeMock.swift
- SplitTests/Fake/Streaming/SynchronizerSpy.swift
- SplitTests/Fake/Streaming/SynchronizerStub.swift
- SplitTests/Helpers/IntegrationHelper.swift
- SplitTests/Helpers/TestSplitFactory.swift
- SplitTests/Helpers/TestingHelper.swift
- SplitTests/Service/MySegments/MySegmentsSyncWorkerTest.swift
- SplitTests/Service/MySegments/PeriodicMySegmentsSyncWorkerTest.swift
- SplitTests/Service/Splits/PeriodicSplitsSyncWorkerTest.swift
- SplitTests/SplitClientManagerTest.swift
- SplitTests/Streaming/ByKeyFacadeTest.swift
- SplitTests/Streaming/FeatureFlagsSynchronizerTest.swift
- SplitTests/Streaming/ImpressionsTrackerTest.swift
- SplitTests/Streaming/MySegmentsSynchronizerTest.swift
- SplitTests/Streaming/PushNotificationManagerTest.swift
- SplitTests/Streaming/SynchronizerTest.swift
- SplitTests/TreatmentManagerTest.swift
> SDKS-8661: Updated tests to run with MLS integrated

- Split.xcodeproj/project.pbxproj
- Split/Events/SplitEventsManager.swift
- Split/FetcherEngine/Refresh/RetryableSyncWorker.swift
- Split/Network/RestClient/RestClient+MyLargeSegments.swift
- Split/Network/Results/MyLargeSegmentsChange.swift
- Split/Network/Results/SegmentsChange.swift
- Split/Network/Sync/SyncManager.swift
- Split/Storage/MySegments/MyLargeSegmentsStorage.swift
- SplitTests/Integration/Api/SplitIntegrationTest.swift
- SplitTests/Integration/Cache/ReadyFromCacheTest.swift
- SplitTests/Service/Splits/PeriodicSplitsSyncWorkerTest.swift
- SplitTests/Storage/MyLargeSegmentsStorageTests.swift
- Fixed issues when fetching and parsing my large segments
- Added SDK ready and ready from cache tests
> SDKS-8661: My large segments tests and some fetcher issues fixes

- Split.xcodeproj/project.pbxproj
- Split/Api/InternalSplitClient.swift
- Split/Api/SplitClientManager.swift
- Split/Engine/Evaluator.swift
- Split/Localhost/LocalhostClientManager.swift
- Split/Matchers/InSegmentMatcher.swift
- Split/Models/Matcher.swift
- Split/Models/MatcherType.swift
- SplitTests/EvaluatorTests.swift
- SplitTests/Fake/InternalSplitClientStub.swift
- SplitTests/Integration/Recorder/TelemetryTest.swift
- SplitTests/Localhost/LocalhostSplitClientTests.swift
- SplitTests/Resources/in_large_segment_whitelist_split.json
- SplitTests/TreatmentManagerTest.swift
Added in large segments matcher and tests
> SDKS-8665: In large segments matcher added

- Split/Network/Streaming/DefaultSseNotificationParser.swift
- Split/Network/Streaming/SseNotifications.swift
- SplitTests/Fake/Streaming/SseNotificationParserStub.swift
- SplitTests/Streaming/NotificationParserTest.swift
- Added My Large segment streaming notification and parser
> SDKS-8665: Large siempre notification and parser

- Split/FetcherEngine/Refresh/BackgroundSyncWorker.swift
- Split/FetcherEngine/Refresh/PeriodicSyncWorker.swift
- Split/FetcherEngine/Refresh/RetryableSyncWorker.swift
- Split/FetcherEngine/Refresh/SplitBgSynchronizer.swift
- Split/Initialization/SplitComponentFactory.swift
- Split/Models/Segment.swift
- Split/Network/Endpoints/EndpointFactory.swift
- Split/Network/Results/AllSegmentsChange.swift
- Split/Network/Results/SegmentsChange.swift
- Split/Network/Streaming/RetryableSplitsUpdateWorkerFactory.swift
- Split/Network/Streaming/SyncSegmentsUpdateWorker.swift
- Split/Network/Sync/SyncManagerBuilder.swift
> SDKS-8751: Unifying Segments endpoint

- Split.xcodeproj/project.pbxproj
- SplitTests/Fake/HttpMySegmentsFetcherStub.swift
- SplitTests/Fake/MySegmentsSyncWorkerFactoryStub.swift
- SplitTests/Fake/Network/RestClientStub.swift
- SplitTests/Fake/Service/ChangesCheckerMock.swift
- SplitTests/Fake/Service/SegmentsSyncHelperMock.swift
- SplitTests/Fake/SplitEventsManagerMock.swift
- SplitTests/Helpers/TestingHelper.swift
- SplitTests/Service/MySegments/HttpMySegmentsFetcherTest.swift
- SplitTests/Service/MySegments/MySegmentsSyncWorkerTest.swift
- SplitTests/Service/MySegments/PeriodicMySegmentsSyncWorkerTest.swift
- SplitTests/Service/MySegments/SegmentsSyncHelperTests.swift
> Updated tests due to CDN Bypass logic

- Split/Api/SplitClientManager.swift
- Split/Common/ServiceConstants.swift
- Split/Common/Structs/ConcurrentDictionary.swift
- Split/Common/Utils/Spec.swift
- Split/Common/Utils/ThreadUtils.swift
- Split/Network/Results/AllSegmentsChange.swift
- Split/Network/Streaming/SseNotifications.swift
- Split/Network/Streaming/SyncSegmentsUpdateWorker.swift
- Split/Network/Streaming/Timers.swift
- Split/Network/Sync/ByKeyFacade.swift
- Split/Network/Sync/MySegmentsSynchronizer.swift
- Split/Network/Sync/Synchronizer.swift
- Added delay logic to memberships notification
> SDKS-8752: Memberships delay notification logic

- Split/Api/SplitClientManager.swift
- Split/Api/SplitDatabaseHelper.swift
- Split/Matchers/InSegmentMatcher.swift
- Split/Models/Extensions/SplitModels+StringConvertible.swift
- Split/Models/Matcher.swift
- Split/Models/UserDefinedSegmentMatcherData.swift
- Split/Models/WhitelistMatcherData.swift
- Split/Network/Streaming/SyncSegmentsUpdateWorker.swift
- Split/Network/Sync/MySegmentsSynchronizer.swift
- Split/Storage/MySegments/MySegmentsStorage.swift
> SDKS- 8752: My large segments matcher logic updated to work with new matcher definition in Split JSON

- Split.xcodeproj/project.pbxproj
- Split.xcodeproj/xcshareddata/xcschemes/Split.xcscheme
- SplitTests/Fake/Service/ByKeyFacadeMock.swift
- SplitTests/Fake/Service/MySegmentsSynchronizerStub.swift
- SplitTests/Fake/Streaming/SynchronizerSpy.swift
- SplitTests/Fake/Streaming/SynchronizerStub.swift
- SplitTests/Fake/Streaming/TimersManagerMock.swift
- SplitTests/Fake/SyncWorkerStub.swift
- SplitTests/Helpers/TestingData.swift
- SplitTests/Helpers/TestingHelper.swift
- SplitTests/Integration/Cache/InitialCacheTest.swift
- SplitTests/Integration/Cache/ReadyFromCacheTest.swift
- SplitTests/Integration/streaming/SdkUpdateStreamingTest.swift
- SplitTests/Integration/streaming/StreamingMySegmentsSyncTest.swift
- SplitTests/Integration/streaming/StreamingSplitsSyncTest.swift
- SplitTests/Resources/simple_split_change.json
- SplitTests/Streaming/ByKeyFacadeTest.swift
- SplitTests/Streaming/MySegmentsSynchronizerTest.swift
- SplitTests/Streaming/NotificationParserTest.swift
- SplitTests/Streaming/SegmentsUpdateWorkerTests.swift
- SplitTests/Streaming/SseHandlerTest.swift
- SplitTests/Streaming/SseNotificationProcessorTest.swift
- SplitTests/Streaming/SynchronizerTest.swift
> SDKS-8752: Adding and improving tests

- Split/Network/Streaming/Timers.swift
- Split/Network/Sync/MySegmentsSynchronizer.swift
- Split/Storage/Splits/SplitsDecoder.swift
- SplitTests/Fake/Streaming/TimersManagerMock.swift
- SplitTests/Helpers/TestingData.swift
- SplitTests/Integration/Cache/InitialCacheTest.swift
- SplitTests/Integration/Cache/ReadyFromCacheTest.swift
- SplitTests/Integration/MultiClient/MultiClientEvaluationTest.swift
- SplitTests/Integration/Recorder/TelemetryTest.swift
- SplitTests/Integration/Sync/FetchSpecificSplitsTest.swift
- SplitTests/Integration/streaming/MySegmentUpdateTest.swift
- SplitTests/Resources/push_msg-segment_updV2.txt
- SplitTests/Service/MySegments/FetcherThrottleTests.swift
> SDKS-8832: Added some new tests and fixing some delay issues

- Split/Api/FailHelpers.swift
- Split/Api/LocalhostSplitClient.swift
- Split/Api/SplitClient.swift
- SplitTests/Fake/InternalSplitClientStub.swift
- SplitTests/Fake/SplitClientStub.swift
Clients supports new events channel.
> [FME-4224] Events - Clients Update

- Split.podspec
- Split/Common/Utils/Version.swift
> chore: Update version to 3.4.0-rc1

- Split.podspec
- Split/Common/Utils/Version.swift
> chore: Update version to 3.4.0-rc2
